// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba73dda2b6eaf8cf67a4a41811265ab87a9c443dc05465a350784957a6422f27
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/kreuzberg.h");
    let go_include_dir = std::path::Path::new("../../../packages/go/v5/include");
    std::fs::create_dir_all(go_include_dir).expect("Unable to create Go include directory");
    std::fs::copy(format!("include/kreuzberg.h"), go_include_dir.join("kreuzberg.h"))
        .expect("Unable to copy header to Go include directory");
}
