// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:577e8ee0dc6650e9a1f3420090d6dc9da2a91b1195a307fe19653d613770878e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    setupFiles: ["./setup.ts"],
  },
});
