# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: detection
defmodule E2e.DetectionTest do
  use ExUnit.Case, async: false

  describe "detect_mime_bytes_html" do
    test "detect_mime_bytes_html" do
      content = File.read!("../../test_documents/html/html.html")
      {:ok, result} = Xberg.detect_mime_type_from_bytes(content)
    end
  end

  describe "detect_mime_bytes_pdf" do
    test "detect_mime_bytes_pdf" do
      content = File.read!("../../test_documents/pdf/fake_memo.pdf")
      {:ok, result} = Xberg.detect_mime_type_from_bytes(content)
    end
  end

  describe "detect_mime_bytes_png" do
    test "detect_mime_bytes_png" do
      content = File.read!("../../test_documents/images/test_hello_world.png")
      {:ok, result} = Xberg.detect_mime_type_from_bytes(content)
    end
  end

  describe "get_extensions_unknown_mime" do
    test "get_extensions_unknown_mime" do
      assert {:error, _} = Xberg.get_extensions_for_mime("application/x-totally-unknown")
    end
  end
end
