# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: ocr_backend_management
defmodule E2e.OcrBackendManagementTest do
  use ExUnit.Case, async: false

  describe "ocr_backends_clear" do
    test "ocr_backends_clear" do
      result = Kreuzberg.clear_ocr_backends()
    end
  end

  describe "ocr_backends_list" do
    test "ocr_backends_list" do
      result = Kreuzberg.list_ocr_backends()
    end
  end

  describe "ocr_backends_unregister" do
    test "ocr_backends_unregister" do
      result = Kreuzberg.unregister_ocr_backend("nonexistent-backend-xyz")
    end
  end
end
