# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664e7204b3427d8fb5a1d4edcbd64599d8941fbf9fb7b56b279e3ec20e3a82ff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: ocr_backend_management
defmodule E2e.OcrBackendManagementTest do
  use ExUnit.Case, async: false

  describe "ocr_backends_clear" do
    test "ocr_backends_clear" do
      result = Xberg.clear_ocr_backends()
    end
  end

  describe "ocr_backends_list" do
    test "ocr_backends_list" do
      result = Xberg.list_ocr_backends()
    end
  end

  describe "ocr_backends_unregister" do
    test "ocr_backends_unregister" do
      result = Xberg.unregister_ocr_backend("nonexistent-backend-xyz")
    end
  end
end
