# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_embedding_backends" do
    test "list_embedding_backends" do
      result = Xberg.list_embedding_backends()
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Xberg.list_ocr_backends()
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Xberg.list_post_processors()
    end
  end

  describe "list_renderers" do
    test "list_renderers" do
      result = Xberg.list_renderers()
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Xberg.list_validators()
    end
  end
end
