# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Xberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Xberg.list_renderers()
    end
  end
end
