# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:885681d2454efbb5bd176ce1496c3e2cdde5422c3aff937785581f1bc63700f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: renderer_management
defmodule E2e.RendererManagementTest do
  use ExUnit.Case, async: false

  describe "renderers_clear" do
    test "renderers_clear" do
      result = Xberg.clear_renderers()
    end
  end

  describe "renderers_list" do
    test "renderers_list" do
      result = Xberg.list_renderers()
    end
  end
end
