# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4218506c64ad24e68856f686ae31c01797b591b5a6cbc798caff50ed3ad4ab4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: reranker_backend_management
defmodule E2e.RerankerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "clear_reranker_backends" do
    test "clear_reranker_backends" do
      result = Kreuzberg.clear_reranker_backends()
    end
  end

  describe "list_reranker_backends" do
    test "list_reranker_backends" do
      result = Kreuzberg.list_reranker_backends()
    end
  end
end
