# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: reranker_backend_management
defmodule E2e.RerankerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "clear_reranker_backends" do
    test "clear_reranker_backends" do
      result = Kreuzberg.clear_reranker_backends()
    end
  end

  describe "list_reranker_backends" do
    test "list_reranker_backends" do
      result = Kreuzberg.list_reranker_backends()
    end
  end
end
