# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31d260bc59638d29e323f9061d48a3b3bbf368c761b180dd0a13d226334b71ac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      result = Kreuzberg.clear_validators()
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Kreuzberg.list_validators()
    end
  end
end
