# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      result = Xberg.clear_validators()
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Xberg.list_validators()
    end
  end
end
