// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31d260bc59638d29e323f9061d48a3b3bbf368c761b180dd0a13d226334b71ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: code.</summary>
    public class CodeTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_CodeShebangDetection()
        {
            // Test language detection from shebang line via bytes input
            var result = KreuzbergLib.ExtractFileSync("code/script.sh", "text/x-source-code", null);
    Assert.Equal("text/x-source-code", result.MimeType!.Trim());
    Assert.True(result.Content.Length >= 10, "expected length >= 10");
    Assert.Contains("build", result.Content.ToString().ToLower());
    Assert.Contains("clean", result.Content.ToString().ToLower());

        }


    }
}
