// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergConverter;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: post_processor_management.</summary>
    public class PostProcessorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_PostProcessorsClear()
        {
            // Clear all post-processors and verify list is empty
            KreuzbergConverter.ClearPostProcessors();
        }

        [Fact]
        public void Test_PostProcessorsList()
        {
            // List all registered post-processors
            var result = KreuzbergConverter.ListPostProcessors();

        }


    }
}
