// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: registry.</summary>
    public class RegistryTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ListEmbeddingBackends()
        {
            // List embedding backends
            var result = XbergConverter.ListEmbeddingBackends();

        }

        [Fact]
        public void Test_ListOcrBackends()
        {
            // List OCR backends
            var result = XbergConverter.ListOcrBackends();

        }

        [Fact]
        public void Test_ListPostProcessors()
        {
            // List post-processors
            var result = XbergConverter.ListPostProcessors();

        }

        [Fact]
        public void Test_ListRenderers()
        {
            // List renderers
            var result = XbergConverter.ListRenderers();

        }

        [Fact]
        public void Test_ListValidators()
        {
            // List validators
            var result = XbergConverter.ListValidators();

        }


    }
}
