// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2cd3600c35ed033abc963f204cf459a1944d69f8799616e8ecd872f6f56bb9a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: summarization.</summary>
    public class SummarizationTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_SummarizationExtractiveSmoke()
        {
            // TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required.
            var result = KreuzbergLib.ExtractFileSync("text/book_war_and_peace_1p.txt", "", ExtractionConfig.FromJson("{\"summarization\":{\"max_tokens\":80,\"strategy\":\"extractive\"}}"));
    Assert.Equal("text/plain", result.MimeType!.Trim());
            // skipped: field 'summary.text' not available on result type        // skipped: field 'summary.strategy' not available on result type
        }


    }
}
