// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;
/** E2e tests for category: post_processor_management. */
public class PostProcessorManagementTest {
    @BeforeAll
    static void initEnv() {        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }    }

    @Test
    void testPostProcessorsClear() throws Exception {
        // Clear all post-processors and verify list is empty
        Xberg.clearPostProcessors();


    }


    @Test
    void testPostProcessorsList() throws Exception {
        // List all registered post-processors
        var result = Xberg.listPostProcessors();


    }

}
