// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;
/** E2e tests for category: post_processor_management. */
public class PostProcessorManagementTest {
    @BeforeAll
    static void initEnv() {        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }    }

    @Test
    void testPostProcessorsClear() throws Exception {
        // Clear all post-processors and verify list is empty
        Xberg.clearPostProcessors();


    }


    @Test
    void testPostProcessorsList() throws Exception {
        // List all registered post-processors
        var result = Xberg.listPostProcessors();


    }

}
