// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:664e7204b3427d8fb5a1d4edcbd64599d8941fbf9fb7b56b279e3ec20e3a82ff
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;
import org.junit.jupiter.api.BeforeAll;
/** E2e tests for category: validator_management. */
public class ValidatorManagementTest {
    @BeforeAll
    static void initEnv() {        if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
            System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true");
        }    }

    @Test
    void testValidatorsClear() throws Exception {
        // Clear all validators and verify list is empty
        Xberg.clearValidators();


    }


    @Test
    void testValidatorsList() throws Exception {
        // List all registered validators
        var result = Xberg.listValidators();


    }

}
