// Generated by alef. Do not edit by hand.
// swift-format-ignore-file
// This file contains generated FFI glue for trait bridge registration.

import Foundation
import RustBridge

/// Protocol for outbound `Renderer` implementations.
/// Conform your Swift class or struct to this protocol to implement
/// a Rust trait from the host side.
public protocol SwiftRendererBridge: AnyObject {
    func render(doc: InternalDocument) throws -> String
}

/// Internal adapter wrapping a `SwiftRendererBridge` conformer.
/// Marshals Swift types and trait calls to/from the C boundary.
/// Excluded/internal types are serialised to/from JSON strings.
final class SwiftRendererAdapter {
    private let bridge: any SwiftRendererBridge

    init(bridge: any SwiftRendererBridge) {
    self.bridge = bridge
    }

    func renderCall(doc: InternalDocument) -> String {
        do {
        let result = try self.bridge.render(doc)
            return marshal_ok_result(result)
    } catch {
        return marshal_error_result(error)
    }
    }

}

// MARK: - Marshalling helpers

private func marshal_ok_result<T: Encodable>(_ value: T) -> String {
    let encoder = JSONEncoder()
    if let data = try? encoder.encode(value),
       let jsonString = String(data: data, encoding: .utf8) {
        return "{\"ok\": \(jsonString)}"
    }
    return "{\"ok\": null}"
}

private func marshal_error_result(_ error: any Error) -> String {
    let errorString = String(describing: error)
    let encoder = JSONEncoder()
    if let data = try? encoder.encode(errorString),
       let jsonString = String(data: data, encoding: .utf8) {
        return "{\"err\": \(jsonString)}"
    }
    return "{\"err\": \"unknown error\"}"
}

/// Register an outbound `Renderer` plugin.
/// Pass an instance conforming to `SwiftRendererBridge`.
public func registerRenderer(_ bridge: any SwiftRendererBridge) throws {
    let adapter = SwiftRendererAdapter(bridge: bridge)
    // Call into Rust to register the adapter
    try RustBridge.registerRenderer(adapter)
}
