// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ffe91f88e8a01dc40b07f1f831eb201917844cd6c8d6423bece72cfa9063794b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: async

use kreuzberg::extract_bytes;

#[tokio::test]
async fn test_async_extract_bytes_empty_mime() {
    // extract_bytes empty MIME async
    let content = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/text/plain.txt"
    ))
    .expect("test_documents/text/plain.txt must exist");
    let mime_type = r#""#;
    let config_json = serde_json::json!({});
    let config = serde_json::from_value(config_json).unwrap();
    let result = extract_bytes(&content, mime_type, &config).await;
    assert!(result.is_err(), "expected call to fail");
}

#[tokio::test]
async fn test_async_extract_bytes_invalid_mime() {
    // extract_bytes unsupported MIME async
    let content = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/text/plain.txt"
    ))
    .expect("test_documents/text/plain.txt must exist");
    let mime_type = r#"application/x-nonexistent"#;
    let config_json = serde_json::json!({});
    let config = serde_json::from_value(config_json).unwrap();
    let result = extract_bytes(&content, mime_type, &config).await;
    assert!(result.is_err(), "expected call to fail");
}
