// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1d78e2f59aac429e0090e8249a4ece6a16576356c970c858f5d84863875f57cd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: embedding_backend_management

use xberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    let _ = clear_embedding_backends();
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends();
}
