// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:25e9c4d9a77f5aa7e91abfbef63bef93b7a18619696dd4c190178be7267cc4fe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
//! E2e tests for category: mime_utilities

use kreuzberg::{detect_mime_type_from_bytes, get_extensions_for_mime};

#[test]
fn test_mime_detect_bytes() {
    // Detect MIME type from file bytes
    let content = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/pdf/fake_memo.pdf"
    ))
    .expect("test_documents/pdf/fake_memo.pdf must exist");
    let result = detect_mime_type_from_bytes(&content).expect("should succeed");
    assert!(
        format!("{:?}", result).contains(r#"pdf"#),
        "expected to contain: {}",
        r#"pdf"#
    );
}

#[test]
fn test_mime_detect_image() {
    // Detect MIME type from PNG image bytes
    let content = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/images/test_hello_world.png"
    ))
    .expect("test_documents/images/test_hello_world.png must exist");
    let result = detect_mime_type_from_bytes(&content).expect("should succeed");
    assert!(
        format!("{:?}", result).contains(r#"png"#),
        "expected to contain: {}",
        r#"png"#
    );
}

#[test]
fn test_mime_get_extensions() {
    // Get file extensions for a MIME type
    let mime_type = r#"application/pdf"#;
    let result = get_extensions_for_mime(mime_type).expect("should succeed");
    assert!(
        format!("{:?}", result).contains(r#"pdf"#),
        "expected to contain: {}",
        r#"pdf"#
    );
}
