// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: post_processor_management

use kreuzberg::{clear_post_processors, list_post_processors};

#[test]
fn test_post_processors_clear() {
    // Clear all post-processors and verify list is empty
    let _ = clear_post_processors();
}

#[test]
fn test_post_processors_list() {
    // List all registered post-processors
    let _ = list_post_processors();
}
