// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: registry

use xberg::{list_embedding_backends, list_ocr_backends, list_post_processors, list_renderers, list_validators};

#[test]
fn test_list_embedding_backends() {
    // List embedding backends
    let _ = list_embedding_backends();
}

#[test]
fn test_list_ocr_backends() {
    // List OCR backends
    let _ = list_ocr_backends();
}

#[test]
fn test_list_post_processors() {
    // List post-processors
    let _ = list_post_processors();
}

#[test]
fn test_list_renderers() {
    // List renderers
    let _ = list_renderers();
}

#[test]
fn test_list_validators() {
    // List validators
    let _ = list_validators();
}
