// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4218506c64ad24e68856f686ae31c01797b591b5a6cbc798caff50ed3ad4ab4e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: reranker_backend_management

use kreuzberg::{clear_reranker_backends, list_reranker_backends};

#[test]
fn test_clear_reranker_backends() {
    // Clear all reranker backends and verify list is empty
    let _ = clear_reranker_backends();
}

#[test]
fn test_list_reranker_backends() {
    // List all registered reranker backends
    let _ = list_reranker_backends();
}
