// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    let _ = clear_tokenizer_backends();
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends();
}
