// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: validator_management

use xberg::{clear_validators, list_validators};

#[test]
fn test_validators_clear() {
    // Clear all validators and verify list is empty
    let _ = clear_validators();
}

#[test]
fn test_validators_list() {
    // List all registered validators
    let _ = list_validators();
}
