# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ArchiveMetadata do
  @moduledoc """
  Archive (ZIP/TAR/7Z) metadata.

  Extracted from compressed archive files containing file lists and size information.
  """

  @typedoc "Archive (ZIP/TAR/7Z) metadata."
  @type t :: %__MODULE__{
  format: String.t() | nil,
  file_count: non_neg_integer(),
  file_list: [String.t()],
  total_size: non_neg_integer(),
  compressed_size: non_neg_integer() | nil
  }

  defstruct format: nil,
  file_count: 0,
  file_list: [],
  total_size: 0,
  compressed_size: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
