# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  @typedoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."
  @type t :: %__MODULE__{
  x1: float(),
  y1: float(),
  x2: float(),
  y2: float()
  }

  defstruct x1: 0.0,
  y1: 0.0,
  x2: 0.0,
  y2: 0.0
end
