# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61b2c8938c132132f6ac987a5658fed582bea2f8248dbe1d25aa618e0ec0b375
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.BoundaryReason do
  @moduledoc "Reason for boundary detection."

  @typedoc "Reason for boundary detection."
  @type t :: :start | :page_one_marker | :letterhead_reset | :density_shift | :end_val

  @start :start
  @page_one_marker :page_one_marker
  @letterhead_reset :letterhead_reset
  @density_shift :density_shift
  @end_val :end

  @doc "Start of PDF."
  @spec start() :: t()
  def start, do: @start
  @doc "Page-one marker (\"Page 1\", \"1 of N\") detected."
  @spec page_one_marker() :: t()
  def page_one_marker, do: @page_one_marker
  @doc "Letterhead reset after signature block."
  @spec letterhead_reset() :: t()
  def letterhead_reset, do: @letterhead_reset
  @doc "Text density shift with low bigram overlap."
  @spec density_shift() :: t()
  def density_shift, do: @density_shift
  @doc "End of PDF."
  @spec end_val() :: t()
  def end_val, do: @end_val
end
