# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CacheStats do
  @moduledoc "Aggregate statistics for a xberg cache directory."

  @typedoc "Aggregate statistics for a xberg cache directory."
  @type t :: %__MODULE__{
  total_files: non_neg_integer(),
  total_size_mb: float(),
  available_space_mb: float(),
  oldest_file_age_days: float(),
  newest_file_age_days: float()
  }

  defstruct total_files: 0,
  total_size_mb: 0.0,
  available_space_mb: 0.0,
  oldest_file_age_days: 0.0,
  newest_file_age_days: 0.0
end
