# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:885681d2454efbb5bd176ce1496c3e2cdde5422c3aff937785581f1bc63700f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
  llm: Xberg.LlmConfig.t(),
  prompt: String.t() | nil,
  min_image_area: non_neg_integer()
  }

  defstruct llm: nil,
  prompt: nil,
  min_image_area: 0
end
