# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e21c71a5751b345136e5ca51dea30bbd3862f7fdc63aa50e6b36be84c454e0e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
  llm: Xberg.LlmConfig.t(),
  prompt: String.t() | nil,
  min_image_area: non_neg_integer()
  }

  defstruct llm: nil,
  prompt: nil,
  min_image_area: 0
end
