# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61b2c8938c132132f6ac987a5658fed582bea2f8248dbe1d25aa618e0ec0b375
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Citation do
  @moduledoc """
  A structured citation from a citation block.

  Parsed from entries like:
  `[^srcN]: source, locator, excerpt: "text"`
  """

  @typedoc "A structured citation from a citation block."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  source: String.t() | nil,
  locator: String.t() | nil,
  excerpt: String.t() | nil
  }

  defstruct label: nil,
  source: nil,
  locator: nil,
  excerpt: nil
end
