# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d78e2f59aac429e0090e8249a4ece6a16576356c970c858f5d84863875f57cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  @typedoc "dBASE (DBF) file metadata."
  @type t :: %__MODULE__{
  record_count: non_neg_integer(),
  field_count: non_neg_integer(),
  fields: [Xberg.DbfFieldInfo.t()]
  }

  defstruct record_count: 0,
  field_count: 0,
  fields: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
