# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d78e2f59aac429e0090e8249a4ece6a16576356c970c858f5d84863875f57cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  text: String.t() | nil,
  title: String.t() | nil
  }

  defstruct url: nil,
  text: nil,
  title: nil
end
