# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  @typedoc "A resolved relationship between two nodes in the document tree."
  @type t :: %__MODULE__{
  source: non_neg_integer(),
  target: non_neg_integer(),
  kind: String.t() | nil
  }

  defstruct source: 0,
  target: 0,
  kind: :footnote_reference
end
