# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
  text: String.t() | nil,
  strategy: String.t() | nil,
  token_count: non_neg_integer() | nil
  }

  defstruct text: nil,
  strategy: :extractive,
  token_count: nil
end
