# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
  element_type: String.t() | nil,
  text: String.t() | nil,
  metadata: Xberg.ElementMetadata.t()
  }

  defstruct element_type: :title,
  text: nil,
  metadata: nil
end
