# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d78e2f59aac429e0090e8249a4ece6a16576356c970c858f5d84863875f57cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  @typedoc "EPUB metadata (Dublin Core extensions)."
  @type t :: %__MODULE__{
  coverage: String.t() | nil,
  dc_format: String.t() | nil,
  relation: String.t() | nil,
  source: String.t() | nil,
  dc_type: String.t() | nil,
  cover_image: String.t() | nil
  }

  defstruct coverage: nil,
  dc_format: nil,
  relation: nil,
  source: nil,
  dc_type: nil,
  cover_image: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
