# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
  sheets: [Xberg.ExcelSheet.t()],
  metadata: map(),
  revisions: [Xberg.DocumentRevision.t()] | nil
  }

  defstruct sheets: [],
  metadata: %{},
  revisions: nil
end
