# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
  sheets: [Xberg.ExcelSheet.t()],
  metadata: map(),
  revisions: [Xberg.DocumentRevision.t()] | nil
  }

  defstruct sheets: [],
  metadata: %{},
  revisions: nil
end
