# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExcelSheet do
  @moduledoc """
  Single Excel worksheet.

  Represents one sheet from an Excel workbook with its content
  converted to Markdown format and dimensional statistics.
  """

  @typedoc "Single Excel worksheet."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  markdown: String.t() | nil,
  row_count: non_neg_integer(),
  col_count: non_neg_integer(),
  cell_count: non_neg_integer(),
  table_cells: [[String.t()]] | nil
  }

  defstruct name: nil,
  markdown: nil,
  row_count: 0,
  col_count: 0,
  cell_count: 0,
  table_cells: nil
end
