# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: String.t() | nil
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
