# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionErrorItem do
  @moduledoc "Non-fatal per-input extraction error captured by [`ExtractionResult`]."

  @typedoc "Non-fatal per-input extraction error captured by [`ExtractionResult`]."
  @type t :: %__MODULE__{
  index: non_neg_integer(),
  code: non_neg_integer(),
  error_type: String.t() | nil,
  source: String.t() | nil,
  message: String.t() | nil
  }

  defstruct index: 0,
  code: 0,
  error_type: nil,
  source: nil,
  message: nil
end
