# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  @typedoc "FictionBook (FB2) metadata."
  @type t :: %__MODULE__{
  genres: [String.t()],
  sequences: [String.t()],
  annotation: String.t() | nil
  }

  defstruct genres: [],
  sequences: [],
  annotation: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
