# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61b2c8938c132132f6ac987a5658fed582bea2f8248dbe1d25aa618e0ec0b375
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteAnchor do
  @moduledoc """
  A footnote anchor reference in markdown text.

  Represents a `[^label]` use-site (not a definition).
  """

  @typedoc "A footnote anchor reference in markdown text."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  offset: non_neg_integer()
  }

  defstruct label: nil,
  offset: 0
end
