# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664e7204b3427d8fb5a1d4edcbd64599d8941fbf9fb7b56b279e3ec20e3a82ff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteConfig do
  @moduledoc "Configuration for markdown footnote and citation parsing."

  @typedoc "Configuration for markdown footnote and citation parsing."
  @type t :: %__MODULE__{
  parse_citations: boolean()
  }

  defstruct parse_citations: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
