# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e21c71a5751b345136e5ca51dea30bbd3862f7fdc63aa50e6b36be84c454e0e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FormattedBlock do
  @moduledoc """
  Block-level element in a Djot document.

  Represents structural elements like headings, paragraphs, lists, code blocks, etc.
  """

  @typedoc "Block-level element in a Djot document."
  @type t :: %__MODULE__{
  block_type: String.t() | nil,
  level: non_neg_integer() | nil,
  inline_content: [Xberg.InlineElement.t()],
  language: String.t() | nil,
  code: String.t() | nil,
  children: [Xberg.FormattedBlock.t()]
  }

  defstruct block_type: :paragraph,
  level: nil,
  inline_content: [],
  language: nil,
  code: nil,
  children: []
end
