# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664e7204b3427d8fb5a1d4edcbd64599d8941fbf9fb7b56b279e3ec20e3a82ff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
  headings: [Xberg.HeadingLevel.t()]
  }

  defstruct headings: []
end
