# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
  src: String.t() | nil,
  alt: String.t() | nil,
  title: String.t() | nil,
  image_type: String.t() | nil
  }

  defstruct src: nil,
  alt: nil,
  title: nil,
  image_type: :data_uri
end
