# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d78e2f59aac429e0090e8249a4ece6a16576356c970c858f5d84863875f57cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @typedoc "Keyword algorithm selection."
  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @doc "YAKE (Yet Another Keyword Extractor) - statistical approach"
  @spec yake() :: t()
  def yake, do: @yake
  @doc "RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based"
  @spec rake() :: t()
  def rake, do: @rake
end
