# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d78e2f59aac429e0090e8249a4ece6a16576356c970c858f5d84863875f57cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
  href: String.t() | nil,
  text: String.t() | nil,
  title: String.t() | nil,
  link_type: String.t() | nil,
  rel: [String.t()]
  }

  defstruct href: nil,
  text: nil,
  title: nil,
  link_type: :anchor,
  rel: []
end
