# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MetaSchema do
  @moduledoc "Compiled meta-schema validator over `preset.schema.json`."

  alias Xberg.Native
  defstruct [:ref]

  @typedoc "Compiled meta-schema validator over `preset.schema.json`."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Compile the given JSON text as a Draft 2020-12 meta-schema."
  def compile(meta_schema_json) do
    ref = Native.metaschema_compile(meta_schema_json)
    %__MODULE__{ref: ref}
  end

  @doc "Validate `raw` against the meta-schema and deserialize into a [`Preset`],"
  def parse_preset(obj, path, raw) do
    Native.metaschema_parse_preset(obj.ref, path, raw)
  end
end
