# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
  det_model: String.t() | nil,
  cls_model: String.t() | nil,
  rec_model: String.t() | nil,
  dict_file: String.t() | nil
  }

  defstruct det_model: nil,
  cls_model: nil,
  rec_model: nil,
  dict_file: nil
end
