# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44df7621a52239a822c632ad86d25d572eb9ff921657c2db06767d4dad50098a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
  det_model: String.t() | nil,
  cls_model: String.t() | nil,
  rec_model: String.t() | nil,
  dict_file: String.t() | nil
  }

  defstruct det_model: nil,
  cls_model: nil,
  rec_model: nil,
  dict_file: nil
end
