# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664e7204b3427d8fb5a1d4edcbd64599d8941fbf9fb7b56b279e3ec20e3a82ff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
  page_count: non_neg_integer(),
  pages: [Xberg.PageSignals.t()]
  }

  defstruct page_count: 0,
  pages: []
end
