# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrTable do
  @moduledoc """
  Table detected via OCR.

  Represents a table structure recognized during OCR processing.
  """

  @typedoc "Table detected via OCR."
  @type t :: %__MODULE__{
  cells: [[String.t()]],
  markdown: String.t() | nil,
  page_number: non_neg_integer(),
  bounding_box: Xberg.OcrTableBoundingBox.t() | nil
  }

  defstruct cells: [],
  markdown: nil,
  page_number: 0,
  bounding_box: nil
end
