# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  @typedoc "Rotation information for an OCR element."
  @type t :: %__MODULE__{
  angle_degrees: float(),
  confidence: float() | nil
  }

  defstruct angle_degrees: 0.0,
  confidence: nil
end
