# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61b2c8938c132132f6ac987a5658fed582bea2f8248dbe1d25aa618e0ec0b375
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassification do
  @moduledoc "Classification result for a single page."

  @typedoc "Classification result for a single page."
  @type t :: %__MODULE__{
  page_number: non_neg_integer(),
  labels: [Xberg.ClassificationLabel.t()]
  }

  defstruct page_number: 0,
  labels: []
end
