# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
  prompt_template: String.t() | nil,
  labels: [String.t()],
  multi_label: boolean(),
  llm: Xberg.LlmConfig.t()
  }

  defstruct prompt_template: nil,
  labels: [],
  multi_label: false,
  llm: nil
end
