# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PatternMatch do
  @moduledoc "One detected PII span in the input text."

  @typedoc "One detected PII span in the input text."
  @type t :: %__MODULE__{
  start: non_neg_integer(),
  end: non_neg_integer(),
  category: String.t() | nil,
  text: String.t() | nil
  }

  defstruct start: 0,
  end: 0,
  category: :email,
  text: nil
end
