# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  @typedoc "A PDF annotation extracted from a document page."
  @type t :: %__MODULE__{
  annotation_type: String.t() | nil,
  content: String.t() | nil,
  page_number: non_neg_integer(),
  bounding_box: Xberg.BoundingBox.t() | nil
  }

  defstruct annotation_type: :text,
  content: nil,
  page_number: 0,
  bounding_box: nil
end
