# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  @typedoc "A PDF annotation extracted from a document page."
  @type t :: %__MODULE__{
  annotation_type: String.t() | nil,
  content: String.t() | nil,
  page_number: non_neg_integer(),
  bounding_box: Xberg.BoundingBox.t() | nil
  }

  defstruct annotation_type: :text,
  content: nil,
  page_number: 0,
  bounding_box: nil
end
