# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PptxMetadata do
  @moduledoc """
  PowerPoint presentation metadata.

  Extracted from PPTX files containing slide counts and presentation details.
  """

  @typedoc "PowerPoint presentation metadata."
  @type t :: %__MODULE__{
  slide_count: non_neg_integer(),
  slide_names: [String.t()],
  image_count: non_neg_integer() | nil,
  table_count: non_neg_integer() | nil
  }

  defstruct slide_count: 0,
  slide_names: [],
  image_count: nil,
  table_count: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
