# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61b2c8938c132132f6ac987a5658fed582bea2f8248dbe1d25aa618e0ec0b375
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PropertyChange do
  @moduledoc """
  A single run-level or style-level property change.

  Used for revisions that change formatting rather than text content. `from`
  and `to` store normalized property values when the source format exposes
  them; either side may be absent when the format only records one side of the
  change.
  """

  @typedoc "A single run-level or style-level property change."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  from: String.t() | nil,
  to: String.t() | nil
  }

  defstruct name: nil,
  from: nil,
  to: nil
end
