# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9379f3dd24332d39e85ef273090498a947805776281008364be2c4f996a85527
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionReport do
  @moduledoc """
  Audit report describing what the redaction processor found and how it replaced it.

  The redactor returns this alongside the rewritten content so compliance, replay, and
  audit-log consumers can see exactly what fired. Offsets are relative to the *original*
  pre-redaction `content` and are intended for audit reconstruction only — the original
  bytes are dropped at the end of the pipeline.
  """

  @typedoc "Audit report describing what the redaction processor found and how it replaced it."
  @type t :: %__MODULE__{
  findings: [Xberg.RedactionFinding.t()],
  total_redacted: non_neg_integer()
  }

  defstruct findings: [],
  total_redacted: 0
end
