# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionFinding do
  @moduledoc "One redaction event: which span was rewritten, why, and with what."

  @typedoc "One redaction event: which span was rewritten, why, and with what."
  @type t :: %__MODULE__{
  start: non_neg_integer(),
  end: non_neg_integer(),
  category: String.t() | nil,
  strategy: String.t() | nil,
  replacement_token: String.t() | nil
  }

  defstruct start: 0,
  end: 0,
  category: :email,
  strategy: :mask,
  replacement_token: nil
end
