# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionConfig do
  @moduledoc "Configuration for the redaction post-processor."

  @typedoc "Configuration for the redaction post-processor."
  @type t :: %__MODULE__{
  categories: [String.t() | nil],
  strategy: String.t() | nil,
  ner: Xberg.NerConfig.t() | nil,
  preserve_offsets: boolean(),
  custom_terms: [Xberg.RedactionTerm.t()],
  custom_patterns: [Xberg.RedactionPattern.t()]
  }

  defstruct categories: [],
  strategy: :mask,
  ner: nil,
  preserve_offsets: true,
  custom_terms: [],
  custom_patterns: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
