# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ReductionLevel do
  @moduledoc "Intensity level for the token-reduction pipeline."

  @typedoc "Intensity level for the token-reduction pipeline."
  @type t :: :off | :light | :moderate | :aggressive | :maximum

  @off :off
  @light :light
  @moderate :moderate
  @aggressive :aggressive
  @maximum :maximum

  @doc "No reduction applied; text is returned as-is."
  @spec off() :: t()
  def off, do: @off
  @doc "Remove only the most common stopwords."
  @spec light() :: t()
  def light, do: @light
  @doc "Balanced stopword removal and redundancy filtering."
  @spec moderate() :: t()
  def moderate, do: @moderate
  @doc "Aggressive filtering; may remove less common content words."
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
  @doc "Maximum compression; prioritizes brevity over completeness."
  @spec maximum() :: t()
  def maximum, do: @maximum
end
