# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RevisionDelta do
  @moduledoc """
  The content changes that make up a single revision.

  For insertions and deletions the `content` field carries the added/removed
  lines as `DiffLine::Added` / `DiffLine::Removed` entries. For format
  changes, `property_changes` carries normalized before/after formatting
  values when the source document exposes them.
  """

  @typedoc "The content changes that make up a single revision."
  @type t :: %__MODULE__{
  content: [String.t() | nil],
  table_changes: [Xberg.CellChange.t()],
  property_changes: [Xberg.PropertyChange.t()]
  }

  defstruct content: [],
  table_changes: [],
  property_changes: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
