# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664e7204b3427d8fb5a1d4edcbd64599d8941fbf9fb7b56b279e3ec20e3a82ff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SparseEmbeddingPreset do
  @moduledoc """
  Static metadata for a bundled SPLADE preset (WASM/Android-safe, no ORT).

  Since v5.0.0.
  """

  @typedoc "Static metadata for a bundled SPLADE preset (WASM/Android-safe, no ORT)."
  @type t :: %__MODULE__{
  name: String.t() | nil,
  model_repo: String.t() | nil,
  model_file: String.t() | nil,
  additional_files: [String.t()],
  max_length: non_neg_integer(),
  description: String.t() | nil
  }

  defstruct name: nil,
  model_repo: nil,
  model_file: nil,
  additional_files: [],
  max_length: 0,
  description: nil
end
