# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61b2c8938c132132f6ac987a5658fed582bea2f8248dbe1d25aa618e0ec0b375
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  @typedoc "Structured data (Schema.org, microdata, RDFa) block."
  @type t :: %__MODULE__{
  data_type: String.t() | nil,
  raw_json: String.t() | nil,
  schema_type: String.t() | nil
  }

  defstruct data_type: :json_ld,
  raw_json: nil,
  schema_type: nil
end
