# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9379f3dd24332d39e85ef273090498a947805776281008364be2c4f996a85527
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SummarizationConfig do
  @moduledoc "Configuration for the summarisation post-processor."

  @typedoc "Configuration for the summarisation post-processor."
  @type t :: %__MODULE__{
  strategy: String.t() | nil,
  max_tokens: non_neg_integer() | nil,
  llm: Xberg.LlmConfig.t() | nil
  }

  defstruct strategy: :extractive,
  max_tokens: nil,
  llm: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
