# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Table do
  @moduledoc """
  Extracted table structure.

  Represents a table detected and extracted from a document (PDF, image, etc.).
  Tables are converted to both structured cell data and Markdown format.
  """

  @typedoc "Extracted table structure."
  @type t :: %__MODULE__{
  cells: [[String.t()]],
  markdown: String.t() | nil,
  page_number: non_neg_integer(),
  bounding_box: Xberg.BoundingBox.t() | nil
  }

  defstruct cells: [],
  markdown: nil,
  page_number: 0,
  bounding_box: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
