# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  @typedoc "Token reduction configuration."
  @type t :: %__MODULE__{
  mode: String.t() | nil,
  preserve_important_words: boolean()
  }

  defstruct mode: nil,
  preserve_important_words: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
