# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TranslationConfig do
  @moduledoc "Configuration for the translation post-processor."

  @typedoc "Configuration for the translation post-processor."
  @type t :: %__MODULE__{
  target_lang: String.t() | nil,
  source_lang: String.t() | nil,
  preserve_markup: boolean(),
  llm: Xberg.LlmConfig.t()
  }

  defstruct target_lang: nil,
  source_lang: nil,
  preserve_markup: false,
  llm: nil
end
