# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Translation do
  @moduledoc """
  Translation of the extracted content.

  Holds the translated rendition of `ExtractedDocument::content` and (when
  `preserve_markup` was requested) the translated `formatted_content`. Chunks
  are translated in place inside `ExtractedDocument::chunks[*].content` rather
  than duplicated here.
  """

  @typedoc "Translation of the extracted content."
  @type t :: %__MODULE__{
  target_lang: String.t() | nil,
  source_lang: String.t() | nil,
  content: String.t() | nil,
  formatted_content: String.t() | nil
  }

  defstruct target_lang: nil,
  source_lang: nil,
  content: nil,
  formatted_content: nil
end
