# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61b2c8938c132132f6ac987a5658fed582bea2f8248dbe1d25aa618e0ec0b375
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.UrlExtractionMode do
  @moduledoc "URL extraction mode."

  @typedoc "URL extraction mode."
  @type t :: :auto | :document | :crawl

  @auto :auto
  @document :document
  @crawl :crawl

  @doc "Classify HTTP(S) resources after fetch."
  @spec auto() :: t()
  def auto, do: @auto
  @doc "Treat the URI as a single remote document/page."
  @spec document() :: t()
  def document, do: @document
  @doc "Crawl from the seed URI and extract discovered pages/documents."
  @spec crawl() :: t()
  def crawl, do: @crawl
end
