# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.XlsxAppProperties do
  @moduledoc """
  Application properties from docProps/app.xml for XLSX

  Contains Excel-specific document metadata.
  """

  @typedoc "Application properties from docProps/app.xml for XLSX"
  @type t :: %__MODULE__{
  application: String.t() | nil,
  app_version: String.t() | nil,
  doc_security: integer() | nil,
  scale_crop: boolean() | nil,
  links_up_to_date: boolean() | nil,
  shared_doc: boolean() | nil,
  hyperlinks_changed: boolean() | nil,
  company: String.t() | nil,
  worksheet_names: [String.t()]
  }

  defstruct application: nil,
  app_version: nil,
  doc_security: nil,
  scale_crop: nil,
  links_up_to_date: nil,
  shared_doc: nil,
  hyperlinks_changed: nil,
  company: nil,
  worksheet_names: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
