# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:885681d2454efbb5bd176ce1496c3e2cdde5422c3aff937785581f1bc63700f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
  min: non_neg_integer() | nil,
  max: non_neg_integer() | nil,
  years: [non_neg_integer()]
  }

  defstruct min: nil,
  max: nil,
  years: []
end
