<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f5b93439fcef1b7f3d01ca65705e4f729f248d94b6d44888ac397c6b4d06c7de
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: async. */
final class AsyncTest extends TestCase
{
    /** extract_bytes empty MIME async */
    public function test_async_extract_bytes_empty_mime(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg::extractBytes("text/plain.txt", "", null);
    }

    /** extract_bytes unsupported MIME async */
    public function test_async_extract_bytes_invalid_mime(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg::extractBytes("text/plain.txt", "application/x-nonexistent", null);
    }
}
