<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: ocr_backend_management. */
final class OcrBackendManagementTest extends TestCase
{

    /** Clear all OCR backends and verify list is empty */
    public function test_ocr_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearOcrBackends();


    }


    /** List all registered OCR backends */
    public function test_ocr_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listOcrBackends();


    }


    /** Unregister nonexistent OCR backend gracefully */
    public function test_ocr_backends_unregister(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::unregisterOcrBackend("nonexistent-backend-xyz");


    }

}
