<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44778f17a67226208966d8209ca03d2e7ff71bc791d82857ea57454ec7c3354b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: registry_operations. */
final class RegistryOperationsTest extends TestCase
{

    /** Get file extensions for DOCX MIME type */
    public function test_extensions_docx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");


    }


    /** Get file extensions for HTML MIME type */
    public function test_extensions_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("text/html");


    }


    /** Get file extensions for PDF MIME type */
    public function test_extensions_pdf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("application/pdf");


    }

}
