<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:25e9c4d9a77f5aa7e91abfbef63bef93b7a18619696dd4c190178be7267cc4fe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: registry. */
final class RegistryTest extends TestCase
{

    /** List document extractors */
    public function test_list_document_extractors(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listDocumentExtractors();


    }


    /** List embedding backends */
    public function test_list_embedding_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listEmbeddingBackends();


    }


    /** List OCR backends */
    public function test_list_ocr_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listOcrBackends();


    }


    /** List post-processors */
    public function test_list_post_processors(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listPostProcessors();


    }


    /** List renderers */
    public function test_list_renderers(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listRenderers();


    }


    /** List validators */
    public function test_list_validators(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listValidators();


    }

}
