<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: renderer_management. */
final class RendererManagementTest extends TestCase
{

    /** Clear all renderers and verify list is empty */
    public function test_renderers_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearRenderers();


    }


    /** List all registered renderers */
    public function test_renderers_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listRenderers();


    }

}
