<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f5a3bbbb36d30fe586b793eb16684dbf84af5aa2374e8438e14740a379552698
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: summarization. */
final class SummarizationTest extends TestCase
{

    /** TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required. */
    public function test_summarization_extractive_smoke(): void
    {
        $config = \Kreuzberg\ExtractionConfig::from_json(json_encode(["summarization" => ["maxTokens" => 80, "strategy" => "extractive"]]));
        $result = Kreuzberg::extractFileSync("text/book_war_and_peace_1p.txt", null, $config);

            $this->assertEquals("text/plain", trim($result->mimeType));
            $this->assertNotEmpty($result->getSummary()->text);
            $this->assertEquals("extractive", trim($result->getSummary()->strategy));


    }

}
