// Generated by alef. Do not edit by hand.
// alef:hash:239a79ef99a0ae5cd8539d0a4c9e61830b1cb4d0b60008ab227fed10749673bd
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg

/**
 * Input signals for confidence scoring.
 *
 * Caller fills these from the extraction result and the LLM response.
 */
data class ConfidenceSignals(
    /** Fraction of pages with usable text in `[0, 1]`. */
    val textCoverage: Float,
    /** Mean OCR per-element recognition confidence; `null` when OCR did not run. */
    val ocrAggregate: Float? = null,
    /** Schema-validation result of the merged output. */
    val schemaCompliance: SchemaCompliance,
)
