// Generated by alef. Do not edit by hand.
// alef:hash:8f3982d1b295ea5114c9bea2560b965ffec390c560650931a3b25d5ed0913b27

package dev.kreuzberg

/// Bridge adapter for IDocumentExtractor implementations.
///
/// Wraps a user-supplied IDocumentExtractor instance and delegates all method calls.
/// This adapter is used internally by the trait bridge registration layer to ensure
/// proper handling of impl instances through JNI boundaries.
internal class DocumentExtractorAdapter(private val impl: IDocumentExtractor) : IDocumentExtractor {
    // Delegate all interface methods to the wrapped implementation
    override fun name(): String = impl.name()

    override fun version(): String = impl.version()

    override fun initialize() = impl.initialize()

    override fun shutdown() = impl.shutdown()

    override fun description(): String = impl.description()

    override fun author(): String = impl.author()

    override fun supportedMimeTypes(): List<String> {
        return impl.supportedMimeTypes()
    }

    override fun priority(): Int {
        return impl.priority()
    }

    override fun canHandle(path: String, mimeType: String): Boolean {
        return impl.canHandle(path, mimeType)
    }


}
