// Generated by alef. Do not edit by hand.
// alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg

/**
 * Application properties from docProps/app.xml for DOCX
 *
 * Contains Word-specific document statistics and metadata.
 */
data class DocxAppProperties(
    /** Application name (e.g., "Microsoft Office Word") */
    val application: String? = null,
    /** Application version */
    val appVersion: String? = null,
    /** Template filename */
    val template: String? = null,
    /** Total editing time in minutes */
    val totalTime: Int? = null,
    /** Number of pages */
    val pages: Int? = null,
    /** Number of words */
    val words: Int? = null,
    /** Number of characters (excluding spaces) */
    val characters: Int? = null,
    /** Number of characters (including spaces) */
    val charactersWithSpaces: Int? = null,
    /** Number of lines */
    val lines: Int? = null,
    /** Number of paragraphs */
    val paragraphs: Int? = null,
    /** Company name */
    val company: String? = null,
    /** Document security level */
    val docSecurity: Int? = null,
    /** Scale crop flag */
    val scaleCrop: Boolean? = null,
    /** Links up to date flag */
    val linksUpToDate: Boolean? = null,
    /** Shared document flag */
    val sharedDoc: Boolean? = null,
    /** Hyperlinks changed flag */
    val hyperlinksChanged: Boolean? = null,
)
