// Generated by alef. Do not edit by hand.
// alef:hash:f5a3bbbb36d30fe586b793eb16684dbf84af5aa2374e8438e14740a379552698
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg

/**
 * A single document returned by the reranker, with its position in the input and score.
 *
 * `index` maps back to the caller's original document list, so metadata arrays
 * (e.g. IDs, paths) can be reordered without passing them through the reranker.
 *
 * Since v5.0.
 */
data class RerankedDocument(
    /** Position of this document in the original input `documents` slice. */
    val index: Long,
    /** Relevance score in `[0, 1]`. Higher means more relevant to the query. */
    val score: Float,
    /** The document text. */
    val document: String,
)
