// Generated by alef. Do not edit by hand.
// alef:hash:f5a3bbbb36d30fe586b793eb16684dbf84af5aa2374e8438e14740a379552698

package dev.kreuzberg

object RerankerBackendBridge {
    private val registered = mutableMapOf<String, IRerankerBackend>()

    fun register(impl: IRerankerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        KreuzbergBridge.nativeRegisterRerankerBackend(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        KreuzbergBridge.nativeUnregisterRerankerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        KreuzbergBridge.nativeClearRerankerBackends()
    }

    fun getAll(): Map<String, IRerankerBackend> = registered.toMap()
}
