// Generated by alef. Do not edit by hand.
// alef:hash:239a79ef99a0ae5cd8539d0a4c9e61830b1cb4d0b60008ab227fed10749673bd
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg

/** Token reduction configuration. */
data class TokenReductionOptions(
    /** Reduction mode: "off", "light", "moderate", "aggressive", "maximum" */
    val mode: String = "",
    /** Preserve important words (capitalized, technical terms) */
    val preserveImportantWords: Boolean = true,
)
