// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8f3982d1b295ea5114c9bea2560b965ffec390c560650931a3b25d5ed0913b27
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: document_extractor_management.
final class DocumentExtractorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testDocumentExtractorsClear() throws {
        // Clear all document extractors and verify list is empty
        let result = try Kreuzberg.clearDocumentExtractors()
    }

    func testExtractorsList() throws {
        // List all registered document extractors
        let result = try Kreuzberg.listDocumentExtractors()
    }

}
