// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a53add0ade534d946ff1d5d8ffe936be35872c213ed418fe15e90e0e45a2a1ee
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: embed_extra.
final class EmbedExtraTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testEmbedTextsBatch() throws {
        // Batch embed texts
        let configObj = try Kreuzberg.embeddingConfigFromJson("{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
        let result = try Kreuzberg.embedTexts(texts: ["Hello", "World"], config: configObj)
    }

}
