// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Tag and audio-property data extracted from an audio/video file.
/// </summary>
public sealed record AudioTags
{
    [JsonPropertyName("title")]
    public string? Title { get; init; } = null;

    /// <summary>
    /// Artist/performer — maps to `Metadata.authors` (wrapped in a Vec).
    /// </summary>
    [JsonPropertyName("artist")]
    public string? Artist { get; init; } = null;

    /// <summary>
    /// Release year as a four-digit string (e.g. "2023") for `Metadata.created_at`.
    /// </summary>
    [JsonPropertyName("year")]
    public string? Year { get; init; } = null;

    /// <summary>
    /// ISO 639 language tag if present in the file (e.g. "eng", "deu").
    /// </summary>
    [JsonPropertyName("language")]
    public string? Language { get; init; } = null;

    /// <summary>
    /// Duration in milliseconds from the file's audio properties.
    /// </summary>
    [JsonPropertyName("duration_ms")]
    public ulong? DurationMs { get; init; } = null;

    /// <summary>
    /// Sample rate in Hz from the file's audio properties.
    /// </summary>
    [JsonPropertyName("sample_rate_hz")]
    public uint? SampleRateHz { get; init; } = null;

    /// <summary>
    /// Channel count from the file's audio properties.
    /// </summary>
    [JsonPropertyName("channels")]
    public ushort? Channels { get; init; } = null;

    /// <summary>
    /// Overall bitrate in kbps from the file's audio properties.
    /// </summary>
    [JsonPropertyName("bitrate")]
    public uint? Bitrate { get; init; } = null;

    /// <summary>
    /// Container format string derived from lofty's `FileType`.
    /// </summary>
    [JsonPropertyName("container")]
    public string? Container { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="AudioTags"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static AudioTags FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<AudioTags>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse AudioTags from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse AudioTags from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
