// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:554bb397ecf14b2cfcc1cbd7e8d9ee406f158a58279fe890a519ee487824e0d3
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
