// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:30fe3e49c9d27a7944962aa5f88d706eb928bc8db88316388f32ffa25c29880f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A drawing object extracted from `<w:drawing>`.
/// </summary>
public sealed class Drawing
{
    [JsonPropertyName("drawing_type")]
    public string DrawingType { get; set; } = "";

    [JsonPropertyName("extent")]
    public string? Extent { get; set; } = null;

    [JsonPropertyName("doc_properties")]
    public string? DocProperties { get; set; } = null;

    [JsonPropertyName("image_ref")]
    public string? ImageRef { get; set; } = null;

}
