// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6e1d9479358586239f5f188ea1746e835d74c730bf88f4443194accc8d1f6126
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Semantic element extracted from document.
///
/// Represents a logical unit of content with semantic classification,
/// unique identifier, and metadata for tracking origin and position.
/// </summary>
public sealed class Element
{
    /// <summary>
    /// Unique element identifier
    /// </summary>
    [JsonPropertyName("element_id")]
    public string ElementId { get; set; } = "";

    /// <summary>
    /// Semantic type of this element
    /// </summary>
    [JsonPropertyName("element_type")]
    public ElementType ElementType { get; set; } = default!;

    /// <summary>
    /// Text content of the element
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// Metadata about the element
    /// </summary>
    [JsonPropertyName("metadata")]
    public ElementMetadata Metadata { get; set; } = default!;

}
