// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:28138e578b34b9ae9677fb879bf8fabbc675369157546babb5c6ed63d593763e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Embedding response containing generated embeddings.
/// </summary>
public sealed class EmbedResponse
{
    /// <summary>
    /// Generated embeddings (one per input text)
    /// </summary>
    [JsonPropertyName("embeddings")]
    public List<List<float>> Embeddings { get; set; } = [];

    /// <summary>
    /// Model used for embedding generation
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = "";

    /// <summary>
    /// Dimensionality of the embeddings
    /// </summary>
    [JsonPropertyName("dimensions")]
    public ulong Dimensions { get; set; } = 0;

    /// <summary>
    /// Number of embeddings generated
    /// </summary>
    [JsonPropertyName("count")]
    public ulong Count { get; set; } = 0;

}
