// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An image manipulation operation (resize, decode, DPI conversion) failed.
/// </summary>
public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
