// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An internal `Mutex` or `RwLock` was found in a poisoned state.
/// </summary>
public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
