// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:836bed2db79d77362e7547b5b6e38a6886e7b623305668f5ea27dc4388eea064
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
