// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a53add0ade534d946ff1d5d8ffe936be35872c213ed418fe15e90e0e45a2a1ee
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// NER backend selector.
/// </summary>
[JsonConverter(typeof(NerBackendKindJsonConverter))]
public enum NerBackendKind
{
    /// <summary>
    /// gline-rs ONNX inference. Requires `ner-onnx` feature. Models download lazily from
    /// HuggingFace via `model_download.hf_download`.
    /// </summary>
    [JsonPropertyName("onnx")]
    Onnx,
    /// <summary>
    /// liter-llm zero-shot NER via structured-output prompts. Requires `ner-llm`
    /// feature. Useful when domain-specific categories outstrip the ONNX taxonomy.
    /// </summary>
    [JsonPropertyName("llm")]
    Llm,
}


/// <summary>
/// Custom JSON converter for <see cref="NerBackendKind"/> that respects explicit variant names.
/// </summary>
internal sealed class NerBackendKindJsonConverter : JsonConverter<NerBackendKind>
{
    public override NerBackendKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "onnx" => NerBackendKind.Onnx,
            "llm" => NerBackendKind.Llm,
            _ => throw new JsonException($"Unknown NerBackendKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, NerBackendKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            NerBackendKind.Onnx => "onnx",
            NerBackendKind.Llm => "llm",
            _ => throw new JsonException($"Unknown NerBackendKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
