// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:016c13498e10f3126396b5857ab0eeb97e970294c01c2e876b01393e449e79b1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class OcrCacheStats
{
    [JsonPropertyName("total_files")]
    public ulong TotalFiles { get; set; } = 0;

    [JsonPropertyName("total_size_mb")]
    public double TotalSizeMb { get; set; } = 0.0;

}
