// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f5a3bbbb36d30fe586b793eb16684dbf84af5aa2374e8438e14740a379552698
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Rotation information for an OCR element.
/// </summary>
public sealed record OcrRotation
{
    /// <summary>
    /// Rotation angle in degrees (0, 90, 180, 270 for PaddleOCR).
    /// </summary>
    [JsonPropertyName("angle_degrees")]
    public double AngleDegrees { get; init; } = 0.0;

    /// <summary>
    /// Confidence score for the rotation detection.
    /// </summary>
    [JsonPropertyName("confidence")]
    public double? Confidence { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="OcrRotation"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static OcrRotation FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<OcrRotation>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse OcrRotation from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse OcrRotation from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
