// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:de30a850d0b97fdf8a03c5d016a7e971dbad53432f314b4de6665989e6623d8c
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
