// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20d91c2b7f3f1b08230c6c46aba06e7b5db0328a77ff7010f697c7a0e244ca99
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Page Segmentation Mode for Tesseract OCR
/// </summary>
public enum PsmMode
{
    [JsonPropertyName("osdonly")]
    OsdOnly,
    [JsonPropertyName("autoosd")]
    AutoOsd,
    [JsonPropertyName("autoonly")]
    AutoOnly,
    [JsonPropertyName("auto")]
    Auto,
    [JsonPropertyName("singlecolumn")]
    SingleColumn,
    [JsonPropertyName("singleblockvertical")]
    SingleBlockVertical,
    [JsonPropertyName("singleblock")]
    SingleBlock,
    [JsonPropertyName("singleline")]
    SingleLine,
    [JsonPropertyName("singleword")]
    SingleWord,
    [JsonPropertyName("circleword")]
    CircleWord,
    [JsonPropertyName("singlechar")]
    SingleChar,
}
