// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c78101d543a6c3060e6667434a9f76623571a6e22bcecb9c85ebd90d3e44cec
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Outlook PST archive metadata.
/// </summary>
public sealed class PstMetadata
{
    [JsonPropertyName("message_count")]
    public ulong MessageCount { get; set; } = 0;

}
