// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f6887c400d7dd35599fdf07cc5734470992e4b0fc7b2e24bf89baceab975d964
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The reranker model or reranking pipeline returned an error.
///
/// Since v5.0.0.
/// </summary>
public class RerankingException : KreuzbergErrorException
{
    public RerankingException(string message) : base(message) { }

    public RerankingException(string message, Exception innerException) : base(message, innerException) { }
}
