// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:db36721f4afcd1c0f569d4957a9d3cbdbe9fc8ed7969379f80a87309427f2be1
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
