// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: ocr_backend_management.
final class OcrBackendManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testOcrBackendsClear() throws {
        // Clear all OCR backends and verify list is empty
        try Xberg.clearOcrBackends()
        // skipped: void-returning function has no result to assert on
    }

    func testOcrBackendsList() throws {
        // List all registered OCR backends
        let result = try Xberg.listOcrBackends()
    }

    func testOcrBackendsUnregister() throws {
        // Unregister nonexistent OCR backend gracefully
        try Xberg.unregisterOcrBackend(name: "nonexistent-backend-xyz")
        // skipped: void-returning function has no result to assert on
    }

}
