// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: post_processor_management.
final class PostProcessorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testPostProcessorsClear() throws {
        // Clear all post-processors and verify list is empty
        try Xberg.clearPostProcessors()
        // skipped: void-returning function has no result to assert on
    }

    func testPostProcessorsList() throws {
        // List all registered post-processors
        let result = try Xberg.listPostProcessors()
    }

}
