// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:664e7204b3427d8fb5a1d4edcbd64599d8941fbf9fb7b56b279e3ec20e3a82ff
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: renderer_management.
final class RendererManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        _ = "true".withCString { val in
            "CRAWLBERG_ALLOW_PRIVATE_NETWORK".withCString { key in
                setenv(key, val, 0)
            }
        }
    }

    func testRenderersClear() throws {
        // Clear all renderers and verify list is empty
        try Xberg.clearRenderers()
        // skipped: void-returning function has no result to assert on
    }

    func testRenderersList() throws {
        // List all registered renderers
        let result = try Xberg.listRenderers()
    }

}
