/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RendererBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  render?(doc: string): string;
}

export class RendererAdapter {
  constructor(private bridge: RendererBridge) {}

  async render(doc: string): Promise<string> {
    try {
      const result = await this.bridge.render(doc);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
