/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RendererBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  render?(doc: string): string;
}

export class RendererAdapter {
  constructor(private bridge: RendererBridge) {}

  async render(doc: string): Promise<string> {
    try {
      const result = await this.bridge.render(doc);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
