# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:239a79ef99a0ae5cd8539d0a4c9e61830b1cb4d0b60008ab227fed10749673bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: pdf

test_that("render_pdf_page_first: render_pdf_page_to_png: first page", {
  result <- render_pdf_page_to_png(pdf_bytes = readBin(.resolve_fixture("pdf/fake_memo.pdf"), what = "raw", n = file.info(.resolve_fixture("pdf/fake_memo.pdf"))$size), page_index = 0, NULL, NULL)
  expect_true(TRUE)
  expect_true(length(result) >= 100)
})

test_that("render_pdf_page_out_of_range: render_pdf_page_to_png: page out of range", {
  expect_error(render_pdf_page_to_png(pdf_bytes = readBin(.resolve_fixture("pdf/fake_memo.pdf"), what = "raw", n = file.info(.resolve_fixture("pdf/fake_memo.pdf"))$size), page_index = 999, NULL, NULL))
})
