# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4218506c64ad24e68856f686ae31c01797b591b5a6cbc798caff50ed3ad4ab4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_extra

test_that("embed_texts_batch: Batch embed texts", {
  result <- embed_texts_async(texts = c("Hello", "World"), config = EmbeddingConfig$from_json(jsonlite::toJSON(list("model" = list("name" = "balanced", "type" = "preset")), auto_unbox = TRUE)))
  expect_true(TRUE)
})
