# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1cf14e1394228c24f50cce267f6049539c7d12f6353eddc6ee6182e89b6b1792
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: validator_management

test_that("validators_clear: Clear all validators and verify list is empty", {
  invisible(clear_validators())
  expect_true(TRUE)
})

test_that("validators_list: List all registered validators", {
  result <- list_validators()
  expect_true(TRUE)
})
