# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e3b9cf3b44bc85b9758c7ae9601b3002859d6b1f51cf6399c843f36d73a1d2d8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: async

test_that("async_extract_bytes_empty_mime: extract_bytes empty MIME async", {
  expect_error(extract_bytes(content = readBin(.resolve_fixture("text/plain.txt"), what = "raw", n = file.info(.resolve_fixture("text/plain.txt"))$size), mime_type = "", config = ExtractionConfig$default()))
})

test_that("async_extract_bytes_invalid_mime: extract_bytes unsupported MIME async", {
  expect_error(extract_bytes(content = readBin(.resolve_fixture("text/plain.txt"), what = "raw", n = file.info(.resolve_fixture("text/plain.txt"))$size), mime_type = "application/x-nonexistent", config = ExtractionConfig$default()))
})
