// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1d78e2f59aac429e0090e8249a4ece6a16576356c970c858f5d84863875f57cd
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : XbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
