// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:44df7621a52239a822c632ad86d25d572eb9ff921657c2db06767d4dad50098a
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : XbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
