// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException
{
    public DeserializeException(string message) : base(message) { }

    public DeserializeException(string message, Exception innerException) : base(message, innerException) { }
}
