// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:44df7621a52239a822c632ad86d25d572eb9ff921657c2db06767d4dad50098a
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
