// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:61b2c8938c132132f6ac987a5658fed582bea2f8248dbe1d25aa618e0ec0b375
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A file system or I/O operation failed. These errors always bubble up unchanged.
/// </summary>
public class IoException : XbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
