// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:885681d2454efbb5bd176ce1496c3e2cdde5422c3aff937785581f1bc63700f1
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while loading or validating a preset file.
/// </summary>
public class LoadErrorException : XbergException
{
    public LoadErrorException(string message) : base(message) { }

    public LoadErrorException(string message, Exception innerException) : base(message, innerException) { }
}
