// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file is not valid JSON.
/// </summary>
public class ParseException : LoadErrorException
{
    public ParseException(string message) : base(message) { }

    public ParseException(string message, Exception innerException) : base(message, innerException) { }
}
