// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException
{
    public PdfAnalysisErrorException(string message) : base(message) { }

    public PdfAnalysisErrorException(string message, Exception innerException) : base(message, innerException) { }
}
