// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The reranker model or reranking pipeline returned an error.
///
/// Since v5.0.0.
/// </summary>
public class RerankingException : XbergErrorException
{
    public RerankingException(string message) : base(message) { }

    public RerankingException(string message, Exception innerException) : base(message, innerException) { }
}
