// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9379f3dd24332d39e85ef273090498a947805776281008364be2c4f996a85527
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException
{
    public ResolveErrorException(string message) : base(message) { }

    public ResolveErrorException(string message, Exception innerException) : base(message, innerException) { }
}
