// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9379f3dd24332d39e85ef273090498a947805776281008364be2c4f996a85527
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException
{
    public SchemaNotObjectException(string message) : base(message) { }

    public SchemaNotObjectException(string message, Exception innerException) : base(message, innerException) { }
}
