// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction operation exceeded the configured time limit.
/// </summary>
public class TimeoutException : XbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
