<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6591ea4a112f5235417f3dbfbe3cc6ea17a03ee57dd858d80b15f2fc2f865947
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Kreuzberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Create a fresh counter with no previous state.
     */
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
