// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2cd3600c35ed033abc963f204cf459a1944d69f8799616e8ecd872f6f56bb9a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: post_processor_management. */
public class PostProcessorManagementTest {

    @Test
    void testPostProcessorsClear() throws Exception {
        // Clear all post-processors and verify list is empty
        Kreuzberg.clearPostProcessors();


    }


    @Test
    void testPostProcessorsList() throws Exception {
        // List all registered post-processors
        var result = Kreuzberg.listPostProcessors();


    }

}
