// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31d260bc59638d29e323f9061d48a3b3bbf368c761b180dd0a13d226334b71ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: registry. */
class RegistryTest {

    @Test
    void testListDocumentExtractors() throws Exception {
        // List document extractors
        var result = Kreuzberg.listDocumentExtractors();


    }


    @Test
    void testListEmbeddingBackends() throws Exception {
        // List embedding backends
        var result = Kreuzberg.listEmbeddingBackends();


    }


    @Test
    void testListOcrBackends() throws Exception {
        // List OCR backends
        var result = Kreuzberg.listOcrBackends();


    }


    @Test
    void testListPostProcessors() throws Exception {
        // List post-processors
        var result = Kreuzberg.listPostProcessors();


    }


    @Test
    void testListRenderers() throws Exception {
        // List renderers
        var result = Kreuzberg.listRenderers();


    }


    @Test
    void testListValidators() throws Exception {
        // List validators
        var result = Kreuzberg.listValidators();


    }

}
