# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3db395524349831cabd411eb3abc5b9f614ca45994d548e984b3b0ce18fa0671
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '5.0.0.pre.rc.1'
end
