// DO NOT EDIT - auto-generated by alef
// alef:hash:44778f17a67226208966d8209ca03d2e7ff71bc791d82857ea57454ec7c3354b
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
