// DO NOT EDIT - auto-generated by alef
// alef:hash:f6887c400d7dd35599fdf07cc5734470992e4b0fc7b2e24bf89baceab975d964
package dev.kreuzberg;

/**
 * The extraction was cancelled via a `CancellationToken`.
 */
public class CancelledException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CancelledException with the given message. */
  public CancelledException(final String message) {
    super(message);
  }

  /** Creates a new CancelledException with the given message and cause. */
  public CancelledException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
