// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8f3982d1b295ea5114c9bea2560b965ffec390c560650931a3b25d5ed0913b27
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

/**
 * Classification enrichment knob: how to label the document.
 */
public record ClassificationEnrichmentConfig(PageClassificationConfig config) {
}
