// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Semantic element type classification.
 *
 * Categorizes text content into semantic units for downstream processing.
 * Supports the element types commonly found in Unstructured documents.
 */
@SuppressWarnings("PMD")
public enum ElementType {
    /**
     * Document title
     */
    Title("title"),
    /**
     * Main narrative text body
     */
    NarrativeText("narrative_text"),
    /**
     * Section heading
     */
    Heading("heading"),
    /**
     * List item (bullet, numbered, etc.)
     */
    ListItem("list_item"),
    /**
     * Table element
     */
    Table("table"),
    /**
     * Image element
     */
    Image("image"),
    /**
     * Page break marker
     */
    PageBreak("page_break"),
    /**
     * Code block
     */
    CodeBlock("code_block"),
    /**
     * Block quote
     */
    BlockQuote("block_quote"),
    /**
     * Footer text
     */
    Footer("footer"),
    /**
     * Header text
     */
    Header("header");


    /** The string value. */
    private final String value;

    ElementType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ElementType fromValue(final String value) {
        for (ElementType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ElementType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
