// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8f3982d1b295ea5114c9bea2560b965ffec390c560650931a3b25d5ed0913b27
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Error metadata (for batch operations).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorMetadata.Builder.class)
public record ErrorMetadata(
    @JsonProperty("error_type") String errorType,
    @JsonProperty("message") String message
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("error_type")
private String errorType = "";
private String message = "";

        /** Sets the errorType field. */
        @JsonProperty("error_type")
        public Builder withErrorType(final String value) {
            this.errorType = value;
            return this;
        }

        /** Sets the message field. */
        @JsonProperty("message")
        public Builder withMessage(final String value) {
            this.message = value;
            return this;
        }

        /** Builds the ErrorMetadata instance. */
        public ErrorMetadata build() {
            return new ErrorMetadata(
                errorType,
                message
            );
        }
    }
    // CPD-ON
}
