// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a076e814c5ee666fb6080cdf8c221857d4dc1192495fbe52526ecfa6056c4535
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

/** Exception thrown when input validation fails. */
@SuppressWarnings("checkstyle:LineLength")
public class InvalidInputException extends KreuzbergRsException {
    /** Creates a new InvalidInputException. */
    public InvalidInputException(final String message) {
        super(1, message);
    }

    /** Creates a new InvalidInputException with a cause. */
    public InvalidInputException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
