// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31d260bc59638d29e323f9061d48a3b3bbf368c761b180dd0a13d226334b71ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Keyword algorithm selection.
 */
public enum KeywordAlgorithm {
    /** YAKE (Yet Another Keyword Extractor) - statistical approach */
    Yake("yake"),
    /** RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based */
    Rake("rake");

    /** The string value. */
    private final String value;

    KeywordAlgorithm(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static KeywordAlgorithm fromValue(final String value) {
        for (KeywordAlgorithm e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
