// DO NOT EDIT - auto-generated by alef
// alef:hash:53b2e80bb7288b480a086fbe0eadf6c59df604e5fe2c24adc9cce67ba740bdd3
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
