// DO NOT EDIT - auto-generated by alef
// alef:hash:6591ea4a112f5235417f3dbfbe3cc6ea17a03ee57dd858d80b15f2fc2f865947
package dev.kreuzberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
