// DO NOT EDIT - auto-generated by alef
// alef:hash:f5a3bbbb36d30fe586b793eb16684dbf84af5aa2374e8438e14740a379552698
package dev.kreuzberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) {
    super(message);
  }

  /** Creates a new PdfAnalysisErrorException with the given message and cause. */
  public PdfAnalysisErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
