// DO NOT EDIT - auto-generated by alef
// alef:hash:2cd3600c35ed033abc963f204cf459a1944d69f8799616e8ecd872f6f56bb9a2
package dev.kreuzberg;

/**
 * A registered plugin returned an error during extraction.
 */
public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
