// DO NOT EDIT - auto-generated by alef
// alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
package dev.kreuzberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
