// DO NOT EDIT - auto-generated by alef
// alef:hash:6591ea4a112f5235417f3dbfbe3cc6ea17a03ee57dd858d80b15f2fc2f865947
package dev.kreuzberg;

/**
 * The extraction operation exceeded the configured time limit.
 */
public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
