// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a076e814c5ee666fb6080cdf8c221857d4dc1192495fbe52526ecfa6056c4535
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;
import java.lang.foreign.Arena;

/**
 * Per-category running counter for RedactionStrategy.TokenReplace.
 */
public class TokenCounter implements AutoCloseable {
    private final MemorySegment handle;

    TokenCounter(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    public static TokenCounter create() throws KreuzbergRsException {
        try (var arena = Arena.ofShared()) {
            var handle = (MemorySegment) NativeLib.KREUZBERG_TOKEN_COUNTER_NEW.invoke();
            if (handle == null || handle.equals(MemorySegment.NULL)) {
                throw new KreuzbergRsException("create returned null", (Throwable) null);
            }
            return new TokenCounter(handle);
        }
        catch (Throwable e) {
            if (e instanceof KreuzbergRsException) throw (KreuzbergRsException) e;
            throw new RuntimeException("create failed: " + e.getMessage(), e);
        }
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_TOKEN_COUNTER_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free TokenCounter: " + e.getMessage(), e);
            }
        }
    }
}
