// DO NOT EDIT - auto-generated by alef
// alef:hash:a076e814c5ee666fb6080cdf8c221857d4dc1192495fbe52526ecfa6056c4535
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
