// DO NOT EDIT - auto-generated by alef
// alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
package dev.kreuzberg;

/**
 * Invalid configuration or input parameters were supplied.
 */
public class ValidationException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ValidationException with the given message. */
  public ValidationException(final String message) {
    super(message);
  }

  /** Creates a new ValidationException with the given message and cause. */
  public ValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
