# Generated by alef. Do not edit by hand.
# alef:hash:885681d2454efbb5bd176ce1496c3e2cdde5422c3aff937785581f1bc63700f1
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.** { *; }
