// Generated by alef. Do not edit by hand.
// alef:hash:9379f3dd24332d39e85ef273090498a947805776281008364be2c4f996a85527
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Combined paths to all models needed for OCR (backward compatibility). */
data class ModelPaths(
    /** Path to the detection model directory. */
    val detModel: String,
    /** Path to the classification model directory. */
    val clsModel: String,
    /** Path to the recognition model directory. */
    val recModel: String,
    /** Path to the character dictionary file. */
    val dictFile: String,
)
