// Generated by alef. Do not edit by hand.
// alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75

package io.xberg

object OcrBackendBridge {
    private val registered = mutableMapOf<String, IOcrBackend>()

    fun register(impl: IOcrBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterOcrBackend(OcrBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterOcrBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearOcrBackends()
    }

    fun getAll(): Map<String, IOcrBackend> = registered.toMap()
}
