// Generated by alef. Do not edit by hand.
// alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4

package io.xberg

object PostProcessorBridge {
    private val registered = mutableMapOf<String, IPostProcessor>()

    fun register(impl: IPostProcessor): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterPostProcessor(PostProcessorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterPostProcessor(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearPostProcessors()
    }

    fun getAll(): Map<String, IPostProcessor> = registered.toMap()
}
