// Generated by alef. Do not edit by hand.
// alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Application properties from docProps/app.xml for PPTX
 *
 * Contains PowerPoint-specific document metadata.
 */
data class PptxAppProperties(
    /** Application name (e.g., "Microsoft Office PowerPoint") */
    val application: String? = null,
    /** Application version */
    val appVersion: String? = null,
    /** Total editing time in minutes */
    val totalTime: Int? = null,
    /** Company name */
    val company: String? = null,
    /** Document security level */
    val docSecurity: Int? = null,
    /** Scale crop flag */
    val scaleCrop: Boolean? = null,
    /** Links up to date flag */
    val linksUpToDate: Boolean? = null,
    /** Shared document flag */
    val sharedDoc: Boolean? = null,
    /** Hyperlinks changed flag */
    val hyperlinksChanged: Boolean? = null,
    /** Number of slides */
    val slides: Int? = null,
    /** Number of notes */
    val notes: Int? = null,
    /** Number of hidden slides */
    val hiddenSlides: Int? = null,
    /** Number of multimedia clips */
    val multimediaClips: Int? = null,
    /** Presentation format (e.g., "Widescreen", "Standard") */
    val presentationFormat: String? = null,
    /** Slide titles */
    val slideTitles: List<String> = emptyList(),
)
