// Generated by alef. Do not edit by hand.
// alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * A supported document format entry.
 *
 * Represents a file extension and its corresponding MIME type that Xberg can process.
 */
data class SupportedFormat(
    /** File extension (without leading dot), e.g., "pdf", "docx" */
    val extension: String,
    /** MIME type string, e.g., "application/pdf" */
    val mimeType: String,
)
