// Generated by alef. Do not edit by hand.
// alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Cell-level changes for a pair of tables that share the same index. */
data class TableDiff(
    /** Zero-based index of the table in both `a.tables` and `b.tables`. */
    val fromIndex: Long,
    /** Zero-based index in `b.tables` (equal to `from_index` for same-dimension tables). */
    val toIndex: Long,
    /** Cell-level changes within the table. */
    val cellChanges: List<CellChange> = emptyList(),
)
