// DO NOT EDIT - auto-generated by alef
// alef:hash:25c5d652e1f430677e9a29a9a087a4ddb5f6a711ff6134496c19b8b59c116f13
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
