// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:179476c8cd29d41c4894667dde4cadd65e1e9a2f28a70b63fdd01babea346698
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Cross-extractor content filtering configuration.
 *
 * Controls whether "furniture" content (headers, footers, page numbers,
 * watermarks, repeating text) is included in or stripped from extraction
 * results. Applies across all extractors (PDF, DOCX, RTF, ODT, HTML, etc.)
 * with format-specific implementation.
 *
 * When {@code None} on {@code ExtractionConfig}, each extractor uses its current
 * default behavior unchanged.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ContentFilterConfig(
    /**
     * Include running headers in extraction output.
     *
     * - PDF: Disables top-margin furniture stripping and prevents the layout
     *   model from treating {@code PageHeader}-classified regions as furniture.
     * - DOCX: Includes document headers in text output.
     * - RTF/ODT: Headers already included; this is a no-op when true.
     * - HTML/EPUB: Keeps {@code &lt;header&gt;} element content.
     *
     * Default: {@code false} (headers are stripped or excluded).
     */
    @JsonProperty("include_headers") boolean includeHeaders,
    /**
     * Include running footers in extraction output.
     *
     * - PDF: Disables bottom-margin furniture stripping and prevents the layout
     *   model from treating {@code PageFooter}-classified regions as furniture.
     * - DOCX: Includes document footers in text output.
     * - RTF/ODT: Footers already included; this is a no-op when true.
     * - HTML/EPUB: Keeps {@code &lt;footer&gt;} element content.
     *
     * Default: {@code false} (footers are stripped or excluded).
     */
    @JsonProperty("include_footers") boolean includeFooters,
    /**
     * Enable the heuristic cross-page repeating text detector.
     *
     * When {@code true} (default), text that repeats verbatim across a supermajority
     * of pages is classified as furniture and stripped.  Disable this if brand
     * names or repeated headings are being incorrectly removed by the heuristic.
     *
     * Note: when a layout-detection model is active, the model may independently
     * classify page-header / page-footer regions as furniture on a per-page basis.
     * To preserve those regions, set {@code include_headers = true} and/or
     * {@code include_footers = true} in addition to disabling this flag.
     *
     * Primarily affects PDF extraction.
     *
     * Default: {@code true}.
     */
    @JsonProperty("strip_repeating_text") boolean stripRepeatingText,
    /**
     * Include watermark text in extraction output.
     *
     * - PDF: Keeps watermark artifacts and arXiv identifiers.
     * - Other formats: No effect currently.
     *
     * Default: {@code false} (watermarks are stripped).
     */
    @JsonProperty("include_watermarks") boolean includeWatermarks
) {

    /**
     * Parse a {@code ContentFilterConfig} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ContentFilterConfig fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ContentFilterConfig.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ContentFilterConfig from JSON: " + e.getMessage(), e);
        }
    }
    public static ContentFilterConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
