// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:259be7009d2a1282253daf836ee101006ec3c01185125bebeeb619dda40c25de
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings("checkstyle:LineLength")
public class ConversionErrorException extends KreuzbergRsException {
    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
