// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aae8f5ba51fe73cca81fa193c0cb33c1ac48125009bea220a4a9a32be32a4835
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * CSV/TSV file metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CsvMetadataBuilder.class)
public record CsvMetadata(@JsonProperty("row_count") long rowCount, @JsonProperty("column_count") long columnCount,
        @Nullable String delimiter, @JsonProperty("has_header") boolean hasHeader,
        @Nullable @JsonProperty("column_types") List<String> columnTypes) {
    public static CsvMetadataBuilder builder() {
        return new CsvMetadataBuilder();
    }
}
