// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5973a657fbdfec637bad83d5e705ca949eda92c87c5a78dbf40e3dc7d46ed50a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A detected structural boundary in the text.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectedBoundary(
    /** Byte offset of the start of the line in the original text. */
    @JsonProperty("byte_offset") long byteOffset,
    /** Whether this boundary looks like a header/section title. */
    @JsonProperty("is_header") boolean isHeader
) {
}
