// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:260617d7150b9f8e69155c2db73381240a083c04e1c69aa9e44e8764235828d4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image element in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DjotImage(
        /** Image source URL or path */
        String src,
        /** Alternative text */
        String alt,
        /** Optional title */
        @Nullable String title,
        /** Element attributes */
        @Nullable String attributes) {
}
