// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1b4ead163a7be424d0ba07caa5a690d01d558fc4dc9d76c557ee5a8e68454ee6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Word document metadata.
 *
 * Extracted from DOCX files using shared Office Open XML metadata extraction.
 * Integrates with {@code office_metadata} module for core/app/custom properties.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DocxMetadata(
    /**
     * Core properties from docProps/core.xml (Dublin Core metadata)
     *
     * Contains title, creator, subject, keywords, dates, etc.
     * Shared format across DOCX/PPTX/XLSX documents.
     */
    @Nullable @JsonProperty("core_properties") CoreProperties coreProperties,
    /**
     * Application properties from docProps/app.xml (Word-specific statistics)
     *
     * Contains word count, page count, paragraph count, editing time, etc.
     * DOCX-specific variant of Office application properties.
     */
    @Nullable @JsonProperty("app_properties") DocxAppProperties appProperties,
    /**
     * Custom properties from docProps/custom.xml (user-defined properties)
     *
     * Contains key-value pairs defined by users or applications.
     * Values can be strings, numbers, booleans, or dates.
     */
    @Nullable @JsonProperty("custom_properties") Map<String, Object> customProperties
) {

    /**
     * Parse a {@code DocxMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static DocxMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, DocxMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse DocxMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
