// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0c7f782077d5c358fa9c3f7f9a40b03c1b5fd4b4c07ac8136960db1abdccfd4a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * EPUB metadata (Dublin Core extensions).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EpubMetadataBuilder.class)
public record EpubMetadata(@Nullable String coverage, @Nullable @JsonProperty("dc_format") String dcFormat,
        @Nullable String relation, @Nullable String source, @Nullable @JsonProperty("dc_type") String dcType,
        @Nullable @JsonProperty("cover_image") String coverImage) {
    public static EpubMetadataBuilder builder() {
        return new EpubMetadataBuilder();
    }
}
