// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:43178918d2c1842d36f3dcfafc50127ff868e33315d4c54405989806158243cb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Excel workbook representation.
 *
 * Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
 * extracted content and metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExcelWorkbook.Builder.class)
public record ExcelWorkbook(List<ExcelSheet> sheets, Map<String, String> metadata) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("sheets")
        private List<ExcelSheet> sheets = List.of();
        @JsonProperty("metadata")
        private Map<String, String> metadata = Map.of();

        /** Sets the sheets field. */
        @JsonProperty("sheets")
        public Builder withSheets(final List<ExcelSheet> value) {
            this.sheets = value;
            return this;
        }

        /** Sets the metadata field. */
        @JsonProperty("metadata")
        public Builder withMetadata(final Map<String, String> value) {
            this.metadata = value;
            return this;
        }

        /** Builds the ExcelWorkbook instance. */
        public ExcelWorkbook build() {
            return new ExcelWorkbook(
                sheets,
                metadata
            );
        }
    }
    // CPD-ON
}
