// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:22767fabba32fd0b16f361f2cb781550422091b105f000b14ac32e92c48320c9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Result of HTML extraction with optional images and warnings.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record HtmlExtractionResult(String markdown,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<ExtractedInlineImage> images,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> warnings) {
}
