// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44e92786b7b4754414d12f66441b54452e650c7ea4de36b4b832a92f4188ead6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Image type classification.
 */
public enum ImageType {
    /** Data URI image */
    DataUri("data-uri"),
    /** Inline SVG */
    InlineSvg("inline-svg"),
    /** External image URL */
    External("external"),
    /** Relative path image */
    Relative("relative");

    /** The string value. */
    private final String value;

    ImageType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ImageType fromValue(final String value) {
        for (ImageType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
