// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e36fb294f19a571af2e830375b5c3a8669b67ea542c417c82103638f1db44879
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Server information response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record InfoResponse(String version, @JsonProperty("rust_backend") boolean rustBackend) {
}
