// DO NOT EDIT - auto-generated by alef
// alef:hash:8a697761e0a15b9576cb3e50233995c3053d94d9008d10116251385c2c65f358
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
