// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e024c3f09ab090a7c9f02f5ff2ab0e529e983efe9b8c5190ef8da7982a1908e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Extracted keyword with metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Keyword.Builder.class)
public record Keyword(
    /**
     * The keyword text.
     */
    String text,
    /**
     * Relevance score (higher is better, algorithm-specific range).
     */
    float score,
    /**
     * Algorithm that extracted this keyword.
     */
    KeywordAlgorithm algorithm,
    /**
     * Optional positions where keyword appears in text (character offsets).
     */
    @Nullable List<Long> positions
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("text")
        private String text = "";
        @JsonProperty("score")
        private float score = 0.0f;
        @JsonProperty("algorithm")
        private KeywordAlgorithm algorithm = null;
        @JsonProperty("positions")
        private Optional<List<Long>> positions = Optional.empty();

        /** Sets the text field. */
        @JsonProperty("text")
        public Builder withText(final String value) {
            this.text = value;
            return this;
        }

        /** Sets the score field. */
        @JsonProperty("score")
        public Builder withScore(final float value) {
            this.score = value;
            return this;
        }

        /** Sets the algorithm field. */
        @JsonProperty("algorithm")
        public Builder withAlgorithm(final KeywordAlgorithm value) {
            this.algorithm = value;
            return this;
        }

        /** Sets the positions field. */
        @JsonProperty("positions")
        public Builder withPositions(final @Nullable List<Long> value) {
            this.positions = Optional.ofNullable(value);
            return this;
        }

        /** Builds the Keyword instance. */
        public Keyword build() {
            return new Keyword(
                text,
                score,
                algorithm,
                positions.orElse(null)
            );
        }
    }
    // CPD-ON
}
