// DO NOT EDIT - auto-generated by alef
// alef:hash:eb921bf2c0eae4fd623a432c023de4448d89aab42a7836de79c687492429956a
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
