// DO NOT EDIT - auto-generated by alef
// alef:hash:803b234a8b95804ff4f2324b4072c4f9102374b4e1da5fc2057f9ea49676acf9
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
