// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:74179c56b2b913e679b32b2dee4bc9ddcf69b9ce3d3a3ec1dbc13501a443828b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonPOJOBuilder(withPrefix = "with")
public class OcrCacheStatsBuilder {

    private long totalFiles = 0;
    private double totalSizeMb = 0.0;

    /** Sets the totalFiles field. */
    public OcrCacheStatsBuilder withTotalFiles(final long value) {
        this.totalFiles = value;
        return this;
    }

    /** Sets the totalSizeMb field. */
    public OcrCacheStatsBuilder withTotalSizeMb(final double value) {
        this.totalSizeMb = value;
        return this;
    }

    /** Builds the OcrCacheStats instance. */
    public OcrCacheStats build() {
        return new OcrCacheStats(
            totalFiles,
            totalSizeMb
        );
    }
}
