// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e179e212a75aca126b04eec65d301d11b9f2c774e0cb338e108f8354d64db7c5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * RAKE-specific parameters.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class RakeParamsBuilder {

    private long minWordLength = 0;
    private long maxWordsPerPhrase = 0;

    /** Sets the minWordLength field. */
    public RakeParamsBuilder withMinWordLength(final long value) {
        this.minWordLength = value;
        return this;
    }

    /** Sets the maxWordsPerPhrase field. */
    public RakeParamsBuilder withMaxWordsPerPhrase(final long value) {
        this.maxWordsPerPhrase = value;
        return this;
    }

    /** Builds the RakeParams instance. */
    public RakeParams build() {
        return new RakeParams(
            minWordLength,
            maxWordsPerPhrase
        );
    }
}
