// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d06fc75610e33d23da7575758a2ec2af577410806b65851a4931b05e27a8b941
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Structured data type classification.
 */
public enum StructuredDataType {
    /** JSON-LD structured data */
    JsonLd("json-ld"),
    /** Microdata */
    Microdata("microdata"),
    /** RDFa */
    RDFa("rdfa");

    /** The string value. */
    private final String value;

    StructuredDataType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static StructuredDataType fromValue(final String value) {
        for (StructuredDataType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
