// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5549a218c8993f6548270a76ef5aa11d301b1e82878e53b45a3f788a78e652a3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Token reduction configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class TokenReductionOptionsBuilder {

    private String mode = "";
    private boolean preserveImportantWords = true;

    /** Sets the mode field. */
    public TokenReductionOptionsBuilder withMode(final String value) {
        this.mode = value;
        return this;
    }

    /** Sets the preserveImportantWords field. */
    public TokenReductionOptionsBuilder withPreserveImportantWords(final boolean value) {
        this.preserveImportantWords = value;
        return this;
    }

    /** Builds the TokenReductionOptions instance. */
    public TokenReductionOptions build() {
        return new TokenReductionOptions(mode, preserveImportantWords);
    }
}
