// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8c4759f94cfc2fdf4a2ae90674d0d7b37e3bfc47d03a2eb8356c913fd50e95f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Token reduction configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class TokenReductionOptionsBuilder {

    private String mode = "";
    private boolean preserveImportantWords = true;

    /** Sets the mode field. */
    public TokenReductionOptionsBuilder withMode(final String value) {
        this.mode = value;
        return this;
    }

    /** Sets the preserveImportantWords field. */
    public TokenReductionOptionsBuilder withPreserveImportantWords(final boolean value) {
        this.preserveImportantWords = value;
        return this;
    }

    /** Builds the TokenReductionOptions instance. */
    public TokenReductionOptions build() {
        return new TokenReductionOptions(
            mode,
            preserveImportantWords
        );
    }
}
