// DO NOT EDIT - auto-generated by alef
// alef:hash:fc277581aa9a21fe4c5429ea24e4be5fa95107536ae36711bb4f3465eca6b7a4
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
