# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:53b2e80bb7288b480a086fbe0eadf6c59df604e5fe2c24adc9cce67ba740bdd3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc """
  Batch item for byte array extraction.

  Used with `batch_extract_bytes` and `batch_extract_bytes_sync`
  to represent a single item in a batch extraction job.
  """

  @typedoc "Batch item for byte array extraction."
  @type t :: %__MODULE__{
          content: binary(),
          mime_type: String.t() | nil,
          config: map() | nil
        }

  defstruct content: <<>>,
            mime_type: nil,
            config: nil
end
