# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f3982d1b295ea5114c9bea2560b965ffec390c560650931a3b25d5ed0913b27
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
          llm: map(),
          prompt: String.t() | nil,
          min_image_area: non_neg_integer()
        }

  defstruct llm: nil,
            prompt: nil,
            min_image_area: 0
end
