# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Chunk do
  @moduledoc """
  A text chunk with optional embedding and metadata.

  Chunks are created when chunking is enabled in `ExtractionConfig`. Each chunk
  contains the text content, optional embedding vector (if embedding generation
  is configured), and metadata about its position in the document.
  """

  @typedoc "A text chunk with optional embedding and metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          chunk_type: String.t() | nil,
          embedding: [float()] | nil,
          metadata: map()
        }

  defstruct content: nil,
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
