# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e572725fff96686b5bb750e3a541ae1c2feba5b01943671a9aa5d57ba55280ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentFilterConfig do
  @moduledoc "Cross-extractor content filtering configuration."

  defstruct include_headers: false,
            include_footers: false,
            strip_repeating_text: true,
            include_watermarks: false
end
