# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0bd5c9be864ff6c6ea58a27554414ba3fcdaa5bfc9d31f060ac60926922805e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  @typedoc "CSV/TSV file metadata."
  @type t :: %__MODULE__{
          row_count: non_neg_integer(),
          column_count: non_neg_integer(),
          delimiter: String.t() | nil,
          has_header: boolean(),
          column_types: [String.t()] | nil
        }

  defstruct row_count: 0,
            column_count: 0,
            delimiter: nil,
            has_header: false,
            column_types: nil
end
