# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
