# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2ff45e2ff6b3a1f20bc94f346eaf8997bb2af3c0621897caa9d4d24739265c95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
