# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:21c6bca92617f13623c8ffbc32bca5952bbd6c51078ab3cda03ce1fcc400c8b6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  defstruct record_count: 0,
            field_count: 0,
            fields: []
end
