# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:239a79ef99a0ae5cd8539d0a4c9e61830b1cb4d0b60008ab227fed10749673bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DjotContent do
  @moduledoc """
  Comprehensive Djot document structure with semantic preservation.

  This type captures the full richness of Djot markup, including:
  - Block-level structures (headings, lists, blockquotes, code blocks, etc.)
  - Inline formatting (emphasis, strong, highlight, subscript, superscript, etc.)
  - Attributes (classes, IDs, key-value pairs)
  - Links, images, footnotes
  - Math expressions (inline and display)
  - Tables with full structure

  Available when the `djot` feature is enabled.
  """

  @typedoc "Comprehensive Djot document structure with semantic preservation."
  @type t :: %__MODULE__{
          plain_text: String.t() | nil,
          blocks: [map()],
          metadata: map(),
          tables: [map()],
          images: [map()],
          links: [map()],
          footnotes: [map()]
        }

  defstruct plain_text: nil,
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: []
end
