# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1cf14e1394228c24f50cce267f6049539c7d12f6353eddc6ee6182e89b6b1792
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          attributes: String.t() | nil
        }

  defstruct url: nil,
            text: nil,
            title: nil,
            attributes: nil
end
