# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DocumentNode do
  @moduledoc """
  A single node in the document tree.

  Each node has deterministic `id`, typed `content`, optional `parent`/`children`
  for tree structure, and metadata like page number, bounding box, and content layer.
  """

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          content_layer: String.t() | nil,
          page: non_neg_integer() | nil,
          page_end: non_neg_integer() | nil,
          bbox: map() | nil,
          annotations: [map()],
          attributes: map() | nil
        }

  defstruct content: :title,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
