# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bcf8fd5d4bb9bfee800e434b228b09055f657ee7660da67282a88ace019374c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc "Word document metadata."

  defstruct core_properties: "",
            app_properties: "",
            custom_properties: %{}
end
