# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a076e814c5ee666fb6080cdf8c221857d4dc1192495fbe52526ecfa6056c4535
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          text: String.t() | nil,
          metadata: map()
        }

  defstruct element_type: :title,
            text: nil,
            metadata: nil
end
