# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6591ea4a112f5235417f3dbfbe3cc6ea17a03ee57dd858d80b15f2fc2f865947
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  @typedoc "Configuration for email extraction."
  @type t :: %__MODULE__{
          msg_fallback_codepage: non_neg_integer() | nil
        }

  defstruct msg_fallback_codepage: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
