# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7167c4a4e5baaa11af9487ff75305166a15edd44c8ff1439dee61b17d02d64d2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
