# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7ba309c48930acb9a8510eba379930b99c60b5324dd28d59cd563a9e7cde6662
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
