# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:53b2e80bb7288b480a086fbe0eadf6c59df604e5fe2c24adc9cce67ba740bdd3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  @typedoc "Embedded file descriptor extracted from the PDF name tree."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          data: binary(),
          mime_type: String.t() | nil
        }

  defstruct name: nil,
            data: <<>>,
            mime_type: nil
end
