# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b1c0eb04ee2f199ba8db0adcce2db3d45ec300c223e56e0059e00c7da01b81f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingConfig do
  @moduledoc "Embedding configuration for text chunks."

  defstruct model: :preset,
            normalize: true,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: 0
end
