# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f0f82710840f6b4270569b882a2161b41395c13f9023233e8f51dbf3a18cc3eb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
