# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:58a3cecd9bd8a768260fa8882df0aa235c5506ba4db22acef1d24e4ff0126d8f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  defstruct coverage: "",
            dc_format: "",
            relation: "",
            source: "",
            dc_type: "",
            cover_image: ""
end
