# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  @typedoc "Error metadata (for batch operations)."
  @type t :: %__MODULE__{
          error_type: String.t() | nil,
          message: String.t() | nil
        }

  defstruct error_type: nil,
            message: nil
end
