# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a068c021ecb80209fae9a7031f5c14864b8834fe04303b489ac6a2acf134253b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  defstruct error_type: "",
            message: ""
end
