# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4218506c64ad24e68856f686ae31c01797b591b5a6cbc798caff50ed3ad4ab4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [map()],
          metadata: map(),
          revisions: [map()] | nil
        }

  defstruct sheets: [],
            metadata: %{},
            revisions: nil
end
