# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31d260bc59638d29e323f9061d48a3b3bbf368c761b180dd0a13d226334b71ac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [map()],
          metadata: map(),
          revisions: [map()] | nil
        }

  defstruct sheets: [],
            metadata: %{},
            revisions: nil
end
