# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6f1be366cea59c0d43b98dc3f492e430504681600c16004cf17b5019b6d8fe35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedImage do
  @moduledoc "Extracted image from a document."

  defstruct data: "",
            format: "",
            image_index: 0,
            page_number: nil,
            width: nil,
            height: nil,
            colorspace: nil,
            bits_per_component: nil,
            is_mask: false,
            description: nil,
            ocr_result: nil,
            bounding_box: nil,
            source_path: nil,
            image_kind: nil,
            kind_confidence: nil,
            cluster_id: nil
end
