# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f3982d1b295ea5114c9bea2560b965ffec390c560650931a3b25d5ed0913b27
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @typedoc "How the extracted text was produced."
  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @doc "Text extracted directly from the document's native format (no OCR)."
  @spec native() :: t()
  def native, do: @native
  @doc "All text was obtained via OCR (e.g. scanned image-only PDF)."
  @spec ocr() :: t()
  def ocr, do: @ocr
  @doc "Text came from a combination of native extraction and OCR."
  @spec mixed() :: t()
  def mixed, do: @mixed
end
