# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a86ab39b46159b7a3f3a02c1eb0c48dd8f6603f34d2082d93b861f080e6428d6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  defstruct genres: [],
            sequences: [],
            annotation: ""
end
