# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a53add0ade534d946ff1d5d8ffe936be35872c213ed418fe15e90e0e45a2a1ee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.GlineBackend do
  @moduledoc """
  kreuzberg-gliner-rs ONNX backend wrapper.

  Holds an initialised [`GLiNER<SpanMode>`] behind an `Arc<Mutex<...>>` so the
  model can be safely shared across async tasks (inference is synchronous and
  serialised internally by the mutex).
  """

  @typedoc "kreuzberg-gliner-rs ONNX backend wrapper."
  @type t :: %__MODULE__{
          repo_id: String.t() | nil,
          model_path: String.t() | nil,
          tokenizer_path: String.t() | nil
        }

  defstruct repo_id: nil,
            model_path: nil,
            tokenizer_path: nil
end
