# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f63e624bb43d2d0a54720480cd1ceb3f69f75b5642f928261b2834b3e55c326
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchyConfig do
  @moduledoc "Hierarchy extraction configuration for PDF text structure analysis."

  defstruct enabled: true,
            k_clusters: 3,
            include_bbox: true,
            ocr_coverage_threshold: nil
end
