# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b43c7a6ae44186816c6249cc1a15018f7ed23fdad444d38c30cb2c1572b1ff3b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc "A text block with hierarchy level assignment."

  defstruct text: "",
            font_size: 0.0,
            level: "",
            bbox: nil
end
