# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44778f17a67226208966d8209ca03d2e7ff71bc791d82857ea57454ec7c3354b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.HtmlTheme do
  @moduledoc "Built-in HTML theme selection."

  @typedoc "Built-in HTML theme selection."
  @type t :: :default | :git_hub | :dark | :light | :unstyled

  @default :default
  @git_hub :git_hub
  @dark :dark
  @light :light
  @unstyled :unstyled

  @doc "Sensible defaults: system font stack, neutral colours, readable line measure. CSS custom properties (`--kb-*`) are all defined so user CSS can override individual values."
  @spec default() :: t()
  def default, do: @default
  @doc "GitHub Markdown-inspired palette and spacing."
  @spec git_hub() :: t()
  def git_hub, do: @git_hub
  @doc "Dark background, light text."
  @spec dark() :: t()
  def dark, do: @dark
  @doc "Minimal light theme with generous whitespace."
  @spec light() :: t()
  def light, do: @light
  @doc "No built-in stylesheet emitted. CSS custom properties are still defined on `:root` so user stylesheets can reference `var(--kb-*)` tokens."
  @spec unstyled() :: t()
  def unstyled, do: @unstyled
end
