# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44778f17a67226208966d8209ca03d2e7ff71bc791d82857ea57454ec7c3354b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ImageType do
  @moduledoc "Image type classification."

  @typedoc "Image type classification."
  @type t :: :"data-uri" | :"inline-svg" | :external | :relative

  @data_uri :"data-uri"
  @inline_svg :"inline-svg"
  @external :external
  @relative :relative

  @doc "Data URI image"
  @spec data_uri() :: t()
  def data_uri, do: @data_uri
  @doc "Inline SVG"
  @spec inline_svg() :: t()
  def inline_svg, do: @inline_svg
  @doc "External image URL"
  @spec external() :: t()
  def external, do: @external
  @doc "Relative path image"
  @spec relative() :: t()
  def relative, do: @relative
end
