# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b9dd873b47f4602641173b865bf11b19f13b30d2ef021e954ff6b361ea292d74
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          dimensions: [non_neg_integer()] | nil,
          image_type: String.t() | nil,
          attributes: [[String.t()]]
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
