# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c2279235cb309b946243afd51d362ab9a13ac4d9766f9da10cf79f82e8c3525e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  @typedoc "JATS (Journal Article Tag Suite) metadata."
  @type t :: %__MODULE__{
          copyright: String.t() | nil,
          license: String.t() | nil,
          history_dates: map(),
          contributor_roles: [map()]
        }

  defstruct copyright: nil,
            license: nil,
            history_dates: %{},
            contributor_roles: []
end
