# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f3982d1b295ea5114c9bea2560b965ffec390c560650931a3b25d5ed0913b27
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @typedoc "Keyword algorithm selection."
  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @doc "YAKE (Yet Another Keyword Extractor) - statistical approach"
  @spec yake() :: t()
  def yake, do: @yake
  @doc "RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based"
  @spec rake() :: t()
  def rake, do: @rake
end
