# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14b39b7bd6c40c3f732648c22a60155c3ff292699bc9a931d7764441578d1327
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
