# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a076e814c5ee666fb6080cdf8c221857d4dc1192495fbe52526ecfa6056c4535
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
          det_model: String.t() | nil,
          cls_model: String.t() | nil,
          rec_model: String.t() | nil,
          dict_file: String.t() | nil
        }

  defstruct det_model: nil,
            cls_model: nil,
            rec_model: nil,
            dict_file: nil
end
