# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a5ee8e3b28bb51dd6cb76c898ecef4f86806253cd1cdc2c02c2dd2d26f316e5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc "Configuration for OCR element extraction."

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
