# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:862b5455961bfbc1e46390f18c30c2fed5df868d90d4c7f9d0dd62144b67ff05
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrBackendType do
  @moduledoc "OCR backend types."

  @type t :: :tesseract | :easy_ocr | :paddle_ocr | :custom

  @tesseract :tesseract
  @easy_ocr :easy_ocr
  @paddle_ocr :paddle_ocr
  @custom :custom

  @spec tesseract() :: t()
  def tesseract, do: @tesseract
  @spec easy_ocr() :: t()
  def easy_ocr, do: @easy_ocr
  @spec paddle_ocr() :: t()
  def paddle_ocr, do: @paddle_ocr
  @spec custom() :: t()
  def custom, do: @custom
end
