# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8511820100a1e2d96ffc5012670332f08a7182186380516640742a23b81ce05
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
