# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:53b2e80bb7288b480a086fbe0eadf6c59df604e5fe2c24adc9cce67ba740bdd3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.OcrMetadata do
  @moduledoc """
  OCR processing metadata.

  Captures information about OCR processing configuration and results.
  """

  @typedoc "OCR processing metadata."
  @type t :: %__MODULE__{
          language: String.t() | nil,
          psm: integer(),
          output_format: String.t() | nil,
          table_count: non_neg_integer(),
          table_rows: non_neg_integer() | nil,
          table_cols: non_neg_integer() | nil
        }

  defstruct language: nil,
            psm: 0,
            output_format: nil,
            table_count: 0,
            table_rows: nil,
            table_cols: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
