# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:463a80667aa81c685e59a26ca53198a28637517f05ea917ebfe72e05d1a4dbb1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OutputFormat do
  @moduledoc "Output format for extraction results."

  @type t :: term()

  @type plain :: :plain
  @type markdown :: :markdown
  @type djot :: :djot
  @type html :: :html
  @type json :: :json
  @type structured :: :structured
  @type custom :: %{type: :custom, value_0: term()}
end
