# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageHierarchy do
  @moduledoc """
  Page hierarchy structure containing heading levels and block information.

  Used when PDF text hierarchy extraction is enabled. Contains hierarchical
  blocks with heading levels (H1-H6) for semantic document structure.
  """

  @typedoc "Page hierarchy structure containing heading levels and block information."
  @type t :: %__MODULE__{
          block_count: non_neg_integer(),
          blocks: [map()]
        }

  defstruct block_count: 0,
            blocks: []
end
