# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c096435e73f8fe870b6e1a061d44a3031a9bdcacd18ff9a66e6ba0ea04cc6676
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageStructure do
  @moduledoc "Unified page structure for documents."

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
