# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1637cb5ca87c9271928674eab74895c8204f0e6bd6039830c57a7643bdf9d347
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageInfo do
  @moduledoc "Metadata for individual page/slide/sheet."

  defstruct number: 0,
            title: nil,
            dimensions: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
