# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f3982d1b295ea5114c9bea2560b965ffec390c560650931a3b25d5ed0913b27
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
          prompt_template: String.t() | nil,
          labels: [String.t()],
          multi_label: boolean(),
          llm: map()
        }

  defstruct prompt_template: nil,
            labels: [],
            multi_label: false,
            llm: nil
end
