# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44778f17a67226208966d8209ca03d2e7ff71bc791d82857ea57454ec7c3354b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.PageInfo do
  @moduledoc """
  Metadata for individual page/slide/sheet.

  Captures per-page information including dimensions, content counts,
  and visibility state (for presentations).
  """

  @typedoc "Metadata for individual page/slide/sheet."
  @type t :: %__MODULE__{
          number: non_neg_integer(),
          title: String.t() | nil,
          dimensions: [float()] | nil,
          image_count: non_neg_integer() | nil,
          table_count: non_neg_integer() | nil,
          hidden: boolean() | nil,
          is_blank: boolean() | nil,
          has_vector_graphics: boolean()
        }

  defstruct number: 0,
            title: nil,
            dimensions: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
