# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4218506c64ad24e68856f686ae31c01797b591b5a6cbc798caff50ed3ad4ab4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PdfConfig do
  @moduledoc "PDF-specific configuration."

  @typedoc "PDF-specific configuration."
  @type t :: %__MODULE__{
          extract_images: boolean(),
          extract_tables: boolean(),
          passwords: [String.t()] | nil,
          extract_metadata: boolean(),
          hierarchy: map() | nil,
          extract_annotations: boolean(),
          top_margin_fraction: float() | nil,
          bottom_margin_fraction: float() | nil,
          allow_single_column_tables: boolean(),
          ocr_inline_images: boolean()
        }

  defstruct extract_images: false,
            extract_tables: true,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false,
            ocr_inline_images: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
