# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:25e9c4d9a77f5aa7e91abfbef63bef93b7a18619696dd4c190178be7267cc4fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  @typedoc "Post-processor configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          enabled_processors: [String.t()] | nil,
          disabled_processors: [String.t()] | nil,
          enabled_set: [String.t()] | nil,
          disabled_set: [String.t()] | nil
        }

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
