# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:25e9c4d9a77f5aa7e91abfbef63bef93b7a18619696dd4c190178be7267cc4fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded results.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
          source: String.t() | nil,
          message: String.t() | nil
        }

  defstruct source: nil,
            message: nil
end
