# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:88e303be657228d03a561b953920c351297451af59544dbda6037abe3984bc40
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ProcessingStage do
  @moduledoc """
  Processing stages for post-processors.

  Post-processors are executed in stage order (Early → Middle → Late).
  Use stages to control the order of post-processing operations.
  """

  @typedoc "Processing stages for post-processors."
  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @doc "Early stage - foundational processing."
  @spec early() :: t()
  def early, do: @early
  @doc "Middle stage - content transformation."
  @spec middle() :: t()
  def middle, do: @middle
  @doc "Late stage - final enrichment."
  @spec late() :: t()
  def late, do: @late
end
