# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f05732d9de1484bcb65f8c3b0978bafd13f11175eebe30ccc64ab26e30e4244b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc "A non-fatal warning from a processing pipeline stage."

  defstruct source: "",
            message: ""
end
