# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
          payload: String.t() | nil,
          confidence: float() | nil,
          bbox: map() | nil
        }

  defstruct payload: nil,
            confidence: nil,
            bbox: nil
end
