# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:25e9c4d9a77f5aa7e91abfbef63bef93b7a18619696dd4c190178be7267cc4fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ReductionLevel do
  @moduledoc false

  @type t :: :off | :light | :moderate | :aggressive | :maximum

  @off :off
  @light :light
  @moderate :moderate
  @aggressive :aggressive
  @maximum :maximum

  @spec off() :: t()
  def off, do: @off
  @spec light() :: t()
  def light, do: @light
  @spec moderate() :: t()
  def moderate, do: @moderate
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
  @spec maximum() :: t()
  def maximum, do: @maximum
end
