# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31d260bc59638d29e323f9061d48a3b3bbf368c761b180dd0a13d226334b71ac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ReductionLevel do
  @moduledoc false

  @type t :: :off | :light | :moderate | :aggressive | :maximum

  @off :off
  @light :light
  @moderate :moderate
  @aggressive :aggressive
  @maximum :maximum

  @spec off() :: t()
  def off, do: @off
  @spec light() :: t()
  def light, do: @light
  @spec moderate() :: t()
  def moderate, do: @moderate
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
  @spec maximum() :: t()
  def maximum, do: @maximum
end
