# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4218506c64ad24e68856f686ae31c01797b591b5a6cbc798caff50ed3ad4ab4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RerankerConfig do
  @moduledoc """
  Configuration for the reranking pipeline.

  Controls which model to use, how many results to return, and download/cache
  behavior for local ONNX models.

  Since v5.0.0.
  """

  @typedoc "Configuration for the reranking pipeline."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          top_k: non_neg_integer() | nil,
          batch_size: non_neg_integer(),
          show_download_progress: boolean(),
          cache_dir: String.t() | nil,
          acceleration: map() | nil,
          max_rerank_duration_secs: non_neg_integer() | nil
        }

  defstruct model: :preset,
            top_k: nil,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_rerank_duration_secs: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
