# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RerankedDocument do
  @moduledoc """
  A single document returned by the reranker, with its position in the input and score.

  `index` maps back to the caller's original document list, so metadata arrays
  (e.g. IDs, paths) can be reordered without passing them through the reranker.

  Since v5.0.0.
  """

  @typedoc "A single document returned by the reranker, with its position in the input and score."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          score: float(),
          document: String.t() | nil
        }

  defstruct index: 0,
            score: 0.0,
            document: nil
end
