# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb830a94339070ed595d55aa9e829effebdbeac406d59c567d805977e5f57591
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ResolvedStyle do
  @moduledoc "Fully resolved (flattened) style after walking the inheritance chain."

  defstruct paragraph_properties: "",
            run_properties: ""
end
