# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2cd3600c35ed033abc963f204cf459a1944d69f8799616e8ecd872f6f56bb9a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RevisionKind do
  @moduledoc "Semantic classification of a tracked change."

  @typedoc "Semantic classification of a tracked change."
  @type t :: :insertion | :deletion | :format_change | :comment

  @insertion :insertion
  @deletion :deletion
  @format_change :format_change
  @comment :comment

  @doc "Text or content was inserted."
  @spec insertion() :: t()
  def insertion, do: @insertion
  @doc "Text or content was deleted."
  @spec deletion() :: t()
  def deletion, do: @deletion
  @doc "Run-level formatting (font, size, colour, …) was changed."
  @spec format_change() :: t()
  def format_change, do: @format_change
  @doc "A reviewer comment or annotation."
  @spec comment() :: t()
  def comment, do: @comment
end
