# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:239a79ef99a0ae5cd8539d0a4c9e61830b1cb4d0b60008ab227fed10749673bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  @typedoc "Structured data (Schema.org, microdata, RDFa) block."
  @type t :: %__MODULE__{
          data_type: String.t() | nil,
          raw_json: String.t() | nil,
          schema_type: String.t() | nil
        }

  defstruct data_type: :json_ld,
            raw_json: nil,
            schema_type: nil
end
