# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  @typedoc "Structured data (Schema.org, microdata, RDFa) block."
  @type t :: %__MODULE__{
          data_type: String.t() | nil,
          raw_json: String.t() | nil,
          schema_type: String.t() | nil
        }

  defstruct data_type: :json_ld,
            raw_json: nil,
            schema_type: nil
end
