# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:40e5c67a1833fcb609407f32ded6788d469181c47e728473f97b0629f01c576a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableGrid do
  @moduledoc """
  Structured table grid with cell-level metadata.

  Stores row/column dimensions and a flat list of cells with position info.
  """

  @typedoc "Structured table grid with cell-level metadata."
  @type t :: %__MODULE__{
          rows: non_neg_integer(),
          cols: non_neg_integer(),
          cells: [map()]
        }

  defstruct rows: 0,
            cols: 0,
            cells: []
end
