# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6f992af93883d62b8dec9af32b2c157614f6a565dac4d35054cecf4781ead98b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterProcessConfig do
  @moduledoc """
  Processing options for tree-sitter code analysis.

  Controls which analysis features are enabled when extracting code files.
  """

  @typedoc "Processing options for tree-sitter code analysis."
  @type t :: %__MODULE__{
          structure: boolean(),
          imports: boolean(),
          exports: boolean(),
          comments: boolean(),
          docstrings: boolean(),
          symbols: boolean(),
          diagnostics: boolean(),
          chunk_max_size: non_neg_integer() | nil,
          content_mode: String.t() | nil
        }

  defstruct structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunk_max_size: nil,
            content_mode: :chunks
end
