# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2464efb38260ccdce4da2d05afadc97551adf36becb2411019b14e7fc6ec4c90
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
