// DO NOT EDIT - auto-generated by alef
// alef:hash:78849dc1640b78c3b646cd949a7da5a79ed36698fc1351904396ced799a30ddc
package io.xberg;

/**
 * The meta-schema itself failed to compile.
 */
public class BadMetaSchemaException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new BadMetaSchemaException with the given message. */
    public BadMetaSchemaException(final String message) {
        super(message);
    }

    /** Creates a new BadMetaSchemaException with the given message and cause. */
    public BadMetaSchemaException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
