// DO NOT EDIT - auto-generated by alef
// alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
package io.xberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheException with the given message. */
  public CacheException(final String message) {
    super(message);
  }

  /** Creates a new CacheException with the given message and cause. */
  public CacheException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
