// DO NOT EDIT - auto-generated by alef
// alef:hash:44df7621a52239a822c632ad86d25d572eb9ff921657c2db06767d4dad50098a
package io.xberg;

/**
 * A cache read or write operation failed.
 */
public class CacheException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
