// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends XbergRsException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
