// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends XbergRsException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
