// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4e21c71a5751b345136e5ca51dea30bbd3862f7fdc63aa50e6b36be84c454e0e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Link type classification.
 */
@SuppressWarnings("PMD")
public enum LinkType {
    /**
     * Anchor link (#section)
     */
    Anchor("anchor"),
    /**
     * Internal link (same domain)
     */
    Internal("internal"),
    /**
     * External link (different domain)
     */
    External("external"),
    /**
     * Email link (mailto:)
     */
    Email("email"),
    /**
     * Phone link (tel:)
     */
    Phone("phone"),
    /**
     * Other link type
     */
    Other("other");


    /** The string value. */
    private final String value;

    LinkType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static LinkType fromValue(final String value) {
        for (LinkType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown LinkType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
