// DO NOT EDIT - auto-generated by alef
// alef:hash:4e21c71a5751b345136e5ca51dea30bbd3862f7fdc63aa50e6b36be84c454e0e
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new LoadErrorException with the given message. */
    public LoadErrorException(final String message) {
        super(message);
    }

    /** Creates a new LoadErrorException with the given message and cause. */
    public LoadErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
