// DO NOT EDIT - auto-generated by alef
// alef:hash:1d78e2f59aac429e0090e8249a4ece6a16576356c970c858f5d84863875f57cd
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new LoadErrorException with the given message. */
    public LoadErrorException(final String message) {
        super(message);
    }

    /** Creates a new LoadErrorException with the given message and cause. */
    public LoadErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
