// DO NOT EDIT - auto-generated by alef
// alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
package io.xberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
