// DO NOT EDIT - auto-generated by alef
// alef:hash:e1d6256e7595163b66e41e0568dd43c5bf8743a8557c0ac87d5a1cde068a9216
package io.xberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
