// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31f2498b6515e6b8fd195e375ca4fdd16109221b5bd8533f02d655f3d0bf9be4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Supported languages in PaddleOCR.
 *
 * Maps user-friendly language codes to paddle-ocr-rs language identifiers.
 */
@SuppressWarnings("PMD")
public enum PaddleLanguage {
    /**
     * English
     */
    English("english"),
    /**
     * Simplified Chinese
     */
    Chinese("chinese"),
    /**
     * Japanese
     */
    Japanese("japanese"),
    /**
     * Korean
     */
    Korean("korean"),
    /**
     * German
     */
    German("german"),
    /**
     * French
     */
    French("french"),
    /**
     * Latin script (covers most European languages)
     */
    Latin("latin"),
    /**
     * Cyrillic (Russian and related)
     */
    Cyrillic("cyrillic"),
    /**
     * Traditional Chinese
     */
    TraditionalChinese("traditionalchinese"),
    /**
     * Thai
     */
    Thai("thai"),
    /**
     * Greek
     */
    Greek("greek"),
    /**
     * East Slavic (Russian, Ukrainian, Belarusian)
     */
    EastSlavic("eastslavic"),
    /**
     * Arabic (Arabic, Persian, Urdu)
     */
    Arabic("arabic"),
    /**
     * Devanagari (Hindi, Marathi, Sanskrit, Nepali)
     */
    Devanagari("devanagari"),
    /**
     * Tamil
     */
    Tamil("tamil"),
    /**
     * Telugu
     */
    Telugu("telugu");


    /** The string value. */
    private final String value;

    PaddleLanguage(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PaddleLanguage fromValue(final String value) {
        for (PaddleLanguage e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown PaddleLanguage value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
