// DO NOT EDIT - auto-generated by alef
// alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new ResolveErrorException with the given message. */
    public ResolveErrorException(final String message) {
        super(message);
    }

    /** Creates a new ResolveErrorException with the given message and cause. */
    public ResolveErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
