// DO NOT EDIT - auto-generated by alef
// alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new ResolveErrorException with the given message. */
    public ResolveErrorException(final String message) {
        super(message);
    }

    /** Creates a new ResolveErrorException with the given message and cause. */
    public ResolveErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
