// DO NOT EDIT - auto-generated by alef
// alef:hash:a83cf6d4ae5b7f677ed5cf28d09d3872838586a6c81acc7eccf6c3b5d0507b75
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new SchemaValidationException with the given message. */
    public SchemaValidationException(final String message) {
        super(message);
    }

    /** Creates a new SchemaValidationException with the given message and cause. */
    public SchemaValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
