// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/** Exception thrown by XbergRs. */
public class XbergRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new XbergRsException. */
  public XbergRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new XbergRsException with a cause. */
  public XbergRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
