# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cdddc79cb51f8f817a92ac5d0afc6dbbd96da49081dd600133b26f48c48a6c15
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'async' do
  it 'async_extract_bytes_empty_mime: extract_bytes empty MIME async' do
    expect {
      content = File.read("text/plain.txt").bytes
      Kreuzberg.extract_bytes_async(content, '', Kreuzberg::ExtractionConfig.new())
    }.to raise_error
  end

  it 'async_extract_bytes_invalid_mime: extract_bytes unsupported MIME async' do
    expect {
      content = File.read("text/plain.txt").bytes
      Kreuzberg.extract_bytes_async(content, 'application/x-nonexistent', Kreuzberg::ExtractionConfig.new())
    }.to raise_error
  end
end
