# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5823c2ee8136ff9a2112319ec85739a99378ef198707d4ba6e7df73120253e13
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'embedding_backend_management' do
  it 'embedding_backends_clear: Clear all embedding backends and verify list is empty' do
    Xberg.clear_embedding_backends()

  end

  it 'embedding_backends_list: List all registered embedding backends' do
    result = Xberg.list_embedding_backends()

    expect(result).not_to be_nil
  end
end
