# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:239a79ef99a0ae5cd8539d0a4c9e61830b1cb4d0b60008ab227fed10749673bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'ocr_backend_management' do
  it 'ocr_backends_clear: Clear all OCR backends and verify list is empty' do
    Kreuzberg.clear_ocr_backends()

  end

  it 'ocr_backends_list: List all registered OCR backends' do
    result = Kreuzberg.list_ocr_backends()

    expect(result).not_to be_nil
  end

  it 'ocr_backends_unregister: Unregister nonexistent OCR backend gracefully' do
    Kreuzberg.unregister_ocr_backend('nonexistent-backend-xyz')

  end
end
