# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e21c71a5751b345136e5ca51dea30bbd3862f7fdc63aa50e6b36be84c454e0e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'post_processor_management' do
  it 'post_processors_clear: Clear all post-processors and verify list is empty' do
    Xberg.clear_post_processors()

  end

  it 'post_processors_list: List all registered post-processors' do
    result = Xberg.list_post_processors()

    expect(result).not_to be_nil
  end
end
