# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6591ea4a112f5235417f3dbfbe3cc6ea17a03ee57dd858d80b15f2fc2f865947
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'post_processor_management' do
  it 'post_processors_clear: Clear all post-processors and verify list is empty' do
    Kreuzberg.clear_post_processors()

  end

  it 'post_processors_list: List all registered post-processors' do
    result = Kreuzberg.list_post_processors()

    expect(result).not_to be_nil
  end
end
