# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a076e814c5ee666fb6080cdf8c221857d4dc1192495fbe52526ecfa6056c4535
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'renderer_management' do
  it 'renderers_clear: Clear all renderers and verify list is empty' do
    Kreuzberg.clear_renderers()

  end

  it 'renderers_list: List all registered renderers' do
    result = Kreuzberg.list_renderers()

    expect(result).not_to be_nil
  end
end
