# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f5a3bbbb36d30fe586b793eb16684dbf84af5aa2374e8438e14740a379552698
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

# Change to the configured test-documents directory so that fixture file paths like
# "pdf/fake_memo.pdf" resolve correctly when running rspec from e2e/ruby/.
# spec_helper.rb lives in e2e/ruby/spec/; the fixtures dir resolves three directories up.
_test_documents = File.expand_path('../../../test_documents', __dir__)
Dir.chdir(_test_documents) if Dir.exist?(_test_documents)
