# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536f5d7d51af516dc4900fe95d5ceb48f3ceaf9ecaae0fba149c630bc0620ac0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'summarization' do
  it 'summarization_extractive_smoke: TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required.' do
    result = Kreuzberg.extract_file_sync('text/book_war_and_peace_1p.txt', nil, Kreuzberg::ExtractionConfig.new(summarization: { 'max_tokens' => 80, 'strategy' => 'extractive' }))
    expect(result.mime_type.to_s.strip).to eq('text/plain'.strip)
    expect(result.summary.text.to_s).not_to be_empty
    expect(result.summary.strategy.to_s).to eq('extractive')

  end
end
