// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2baf4518d7c7afc785acc35b6795a3f601ce81a51ef1b466863c7fa33e4f211a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: embed_extra
package e2e_test

import (
	"encoding/json"
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_EmbedTextsBatch(t *testing.T) {
	// Batch embed texts
	var texts []string
	if err := json.Unmarshal([]byte(`["hello","world"]`), &texts); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	var config xberg.EmbeddingConfig
	if err := json.Unmarshal([]byte(`{"model":{"name":"balanced","type":"preset"}}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	_, err := xberg.EmbedTextsAsync(texts, config)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
