// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f5a3bbbb36d30fe586b793eb16684dbf84af5aa2374e8438e14740a379552698
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: ocr_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_OcrBackendsClear(t *testing.T) {
	// Clear all OCR backends and verify list is empty
	_ = kreuzberg.ClearOcrBackends()
}

func Test_OcrBackendsList(t *testing.T) {
	// List all registered OCR backends
	_, err := kreuzberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_OcrBackendsUnregister(t *testing.T) {
	// Unregister nonexistent OCR backend gracefully
	_ = kreuzberg.UnregisterOcrBackend(`nonexistent-backend-xyz`)
}
