// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6591ea4a112f5235417f3dbfbe3cc6ea17a03ee57dd858d80b15f2fc2f865947
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: registry
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_ListDocumentExtractors(t *testing.T) {
	// List document extractors
	_, err := kreuzberg.ListDocumentExtractors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListEmbeddingBackends(t *testing.T) {
	// List embedding backends
	_, err := kreuzberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListOcrBackends(t *testing.T) {
	// List OCR backends
	_, err := kreuzberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListPostProcessors(t *testing.T) {
	// List post-processors
	_, err := kreuzberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListRenderers(t *testing.T) {
	// List renderers
	_, err := kreuzberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListValidators(t *testing.T) {
	// List validators
	_, err := kreuzberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
