// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d8f830747165666d22ce9c6314fb295ffa87f7e291597e87ae5c69194e02223a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import dev.kreuzberg.EmbeddingConfig

/** E2e tests for category: embed_async_pending. */
class EmbedAsyncPendingTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testEmbedTextsAsyncEmptyInput() = runBlocking {
        // embed_texts_async: empty text list
        val result = Kreuzberg.embedTextsAsync(listOf(), null)
        assertEquals(0, result.size, "expected exactly 0 elements")
    }

    @Test
    fun testEmbedTextsAsyncHappy() = runBlocking {
        // embed_texts_async: basic async embedding
        val result = Kreuzberg.embedTextsAsync(listOf("First", "Second"), null)
        assertTrue(result.size >= 2, "expected at least 2 elements")
    }

    @Test
    fun testEmbedTextsAsyncPresetSwitch() = runBlocking {
        // embed_texts_async: preset override
        val config = MAPPER.readValue("{\"embedding_model\":\"default\"}", EmbeddingConfig::class.java)
        val result = Kreuzberg.embedTextsAsync(listOf("Text"), config)
    }

}
