// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a53add0ade534d946ff1d5d8ffe936be35872c213ed418fe15e90e0e45a2a1ee
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: registry_operations. */
class RegistryOperationsTest {
    @Test
    fun testExtensionsDocx() = runBlocking {
        // Get file extensions for DOCX MIME type
        val result = Kreuzberg.getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    @Test
    fun testExtensionsHtml() = runBlocking {
        // Get file extensions for HTML MIME type
        val result = Kreuzberg.getExtensionsForMime("text/html")
    }

    @Test
    fun testExtensionsPdf() = runBlocking {
        // Get file extensions for PDF MIME type
        val result = Kreuzberg.getExtensionsForMime("application/pdf")
    }

}
