// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31d260bc59638d29e323f9061d48a3b3bbf368c761b180dd0a13d226334b71ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: registry_operations. */
class RegistryOperationsTest {
    @Test
    fun testExtensionsDocx() = runBlocking {
        // Get file extensions for DOCX MIME type
        val result = Kreuzberg.getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    @Test
    fun testExtensionsHtml() = runBlocking {
        // Get file extensions for HTML MIME type
        val result = Kreuzberg.getExtensionsForMime("text/html")
    }

    @Test
    fun testExtensionsPdf() = runBlocking {
        // Get file extensions for PDF MIME type
        val result = Kreuzberg.getExtensionsForMime("application/pdf")
    }

}
